- .yarn/versions/34ccfa98.yml
- CODE_OF_CONDUCT.md
I used my email address for the time being and am happy to field COC complaints until we have a formal process for dealing with them internally, but I'd like to circle back to this next week so we can develop one. It shouldn't be that difficult, I just want to make sure we're all on the same page.
> Create a Code of Conduct

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Documentation.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .yarn/versions/bf2d8c76.yml
This PR adds various templates to help contributors.
> GitHub templates

- README.md
> Correct readme links

- packages/react/accessible-icon/src/AccesibleIcon.test.tsx
This one already had a good set of tests. Just added one to check for the `focusable` attribute.
> Tests: AccessibleIcon

- packages/react/dialog/src/Dialog.test.tsx
> Tests: Dialog

- packages/react/alert-dialog/src/AlertDialog.test.tsx
> Test: AlertDialog

- packages/react/accordion/src/Accordion.test.tsx
Added some tests for Accordion. These are not 100% exhaustive but I wanted to get some started to confirm we're all good with the overall approach.
> Tests: Accordion

- packages/react/arrow/src/Arrow.test.tsx
> Test: Arrow

- packages/react/aspect-ratio/src/AspectRatio.test.tsx
Jest DOM doesn't do any sort of layout AFAICT, so testing the core functionality of this one is probably better left to visual testing tools.
> Test: AspectRatio

- packages/react/checkbox/src/Checkbox.test.tsx
> Test: Checkbox

- packages/react/avatar/src/Avatar.test.tsx
> Test: Avatar

- .yarn/versions/f61bc288.yml
- packages/react/utils/src/useCallbackRef.tsx
> [react-utils]: Fix return value from useCallbackRef

- .yarn/versions/c93b64b5.yml
- packages/react/dropdown-menu/src/DropdownMenu.tsx
> [DropdownMenu] Add enter key on trigger

- .yarn/versions/bf99b01a.yml
- package.json
- packages/react/focus-scope/src/FocusScope.test.tsx
- yarn.lock
> Test: FocusScope

- .yarn/versions/23cdd195.yml
- packages/react/focus-scope/src/FocusScope.stories.tsx
- packages/react/focus-scope/src/FocusScope.test.tsx
- packages/react/focus-scope/src/createFocusScope.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
Closes #365
This is an alternate to #369 in order to fix #365.
I think is more explicit as to what we're trying to avoid.
@chaance let me know your thoughts on this one.
> [FocusScope] Fix vanishing blur issue

- .yarn/versions/f87893f1.yml
- packages/react/menu/src/Menu.tsx
@jjenzz that one was my fault, I missed it in the review (https://github.com/radix-ui/primitives/pull/409/files#r567683307)
> Note: better to review with whitespace turned off
> [Menu] Fix missing children

- packages/react/accordion/src/Accordion.stories.tsx
This PR adds a story in `Accordion` for Chromatic purpose.
We can use this whilst we setup Chromatic.
> [Accordion] Add story for Chromatic

- .github/workflows/chromatic.yml
- .storybook/preview.js
- .yarn/versions/1083c33d.yml
- packages/react/accordion/src/Accordion.stories.tsx
Adding Chromatic so we can begin adding visual regression tests.
> Add Chromatic

- .yarn/versions/5863712d.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.test.tsx
- packages/react/accordion/src/Accordion.tsx
~>Note: don't merge as it's based off of #425, I'll add versioning when it gets merged.~
> [Accordion] Add chromatic story

- .github/workflows/chromatic.yml
- .yarn/versions/8bf43ef1.yml
- packages/react/accordion/src/Accordion.stories.tsx
Chromatic is taking screenshots of `main` after we have merged into it which will be using up our screenshot quota. This PR should hopefully prevent that 🤞
> Stop Chromatic from screenshotting main pushes

- packages/react/scroll-area/src/ScrollArea.stories.tsx
And add missing selectors to catch in chromatic story
> [ScrollArea] Fix selector in story

- .yarn/versions/0af82cc1.yml
- packages/react/slot/src/Slot.test.tsx
- packages/react/slot/src/Slot.tsx
> [Slot] Fix event handler composition

- .yarn/versions/ed9c973e.yml
- packages/react/collapsible/package.json
- packages/react/collapsible/src/Collapsible.tsx
- ssr-testing/pages/_app.tsx
- ssr-testing/pages/collapsible.tsx
- ssr-testing/pages/id.tsx
- ssr-testing/pages/index.tsx
- yarn.lock
> Note: This PR builds upon #467 so will need to wait for it to be merged first.
I'll also do the version check once the other one is merged.
> [Collapsible] Use SSR-safe ids

- .yarn/versions/4897bd64.yml
- packages/react/accordion/package.json
- packages/react/accordion/src/Accordion.tsx
- ssr-testing/pages/accordion.tsx
- ssr-testing/pages/index.tsx
- yarn.lock
> Note: This PR builds upon #469 so will need to wait for it to be merged first.
I'll also do the version check once the other one is merged.
> [Accordion] Use SSR-safe ids

- .yarn/versions/e8884f04.yml
- packages/react/alert-dialog/package.json
- packages/react/alert-dialog/src/AlertDialog.tsx
- ssr-testing/pages/alert-dialog.tsx
- ssr-testing/pages/index.tsx
- yarn.lock
> Note: This PR builds upon #471 so will need to wait for it to be merged first.
I'll also do the version check once the other one is merged.
> [AlertDialog] Use SSR-safe ids

- packages/react/alert-dialog/src/AlertDialog.tsx
----------
Change base branch to `main` once #477 is merged. 
----------
> Update context in `AlertDialog`

- packages/react/checkbox/src/Checkbox.tsx
----------
Change base branch to `main` once #477 is merged. 
----------
> Update context in `Checkbox`

- .yarn/versions/8f979779.yml
- packages/react/avatar/src/Avatar.tsx
> Update context in `Avatar`

- .yarn/versions/11126144.yml
- packages/react/dropdown-menu/src/DropdownMenu.tsx
> Update context in `DropownMenu`

- .yarn/versions/ffba6840.yml
- packages/react/collapsible/src/Collapsible.tsx
> Update context in `Collapsible`

- .yarn/versions/6d59142d.yml
- packages/react/roving-focus/package.json
- packages/react/roving-focus/src/RovingFocusGroup.tsx
- ssr-testing/pages/index.tsx
- ssr-testing/pages/roving-focus-group.tsx
- yarn.lock
~This all works, however, I'm not really happy with how the data attributes look now that our ids look like `radix-id-x-y`.
Let's discuss in the morning.~
> [RovingFocus] Use SSR-safe ids

- .yarn/versions/e8fc0b0c.yml
- packages/react/tabs/package.json
- packages/react/tabs/src/Tabs.tsx
- ssr-testing/pages/index.tsx
- ssr-testing/pages/tabs.tsx
- yarn.lock
> [Tabs] Use SSR-safe ids

- .yarn/versions/3a4296a7.yml
- packages/react/dialog/src/Dialog.tsx
> Update context in `Dialog`

- .yarn/versions/8fcc94e2.yml
- packages/react/context-menu/src/ContextMenu.tsx
> Update context in `ContextMenu`

- .yarn/versions/7885e970.yml
- packages/react/menu/src/Menu.tsx
> Update context in `Menu`

- .yarn/versions/0307884e.yml
- packages/react/collection/src/collection.tsx
> Update context in `collection`

- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/use-body-pointer-events/README.md
- packages/react/use-body-pointer-events/package.json
- packages/react/use-body-pointer-events/src/index.ts
- packages/react/use-body-pointer-events/src/useBodyPointerEvents.tsx
- packages/react/utils/src/index.ts
- tsconfig.json
- yarn.lock
> [React utils refactor] new react-use-body-pointer-events package

- .yarn/versions/7dab97d7.yml
- packages/core/popper/src/popper.stories.tsx
- packages/react/popper/package.json
- packages/react/popper/src/Popper.tsx
- packages/react/slider/src/Slider.tsx
- packages/react/tooltip/package.json
- packages/react/tooltip/src/Tooltip.tsx
- packages/react/use-layout-effect/src/useLayoutEffect.tsx
- packages/react/use-rect/README.md
- packages/react/use-rect/package.json
- packages/react/use-rect/src/index.ts
- packages/react/use-rect/src/useRect.tsx
- packages/react/use-size/README.md
- packages/react/use-size/package.json
- packages/react/use-size/src/index.ts
- packages/react/use-size/src/useSize.tsx
- packages/react/utils/src/index.ts
- tsconfig.json
- yarn.lock
> [React utils refactor] react-use-rect & react-use-size

- .github/PULL_REQUEST_TEMPLATE.md
- .yarn/versions/1d457255.yml
Simplifying PR template. Chosen icons are up for debate 😅
> Reduce PR template requirements

- .yarn/versions/b34e64bd.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.test.tsx
- packages/react/accordion/src/Accordion.tsx
- packages/react/alert-dialog/src/AlertDialog.test.tsx
- packages/react/checkbox/src/Checkbox.stories.tsx
- packages/react/checkbox/src/Checkbox.test.tsx
- packages/react/collapsible/package.json
- packages/react/collapsible/src/Collapsible.stories.tsx
- packages/react/collapsible/src/Collapsible.test.tsx
- packages/react/collapsible/src/Collapsible.tsx
- packages/react/dialog/src/Dialog.test.tsx
- packages/react/presence/src/Presence.stories.tsx
- packages/react/presence/src/Presence.tsx
- yarn.lock
- Expose height CSS property on `CollapsibleContent`
- Expose height CSS property on `AccordionPanel`
- Removes transition support from `Presence` to make above possible (removes `requestAnimationFrame`s)
- Fix `Checkbox` Animated story
> [Presence][Collapsible][Accordion] Add height CSS property, remove transition support from Presence

- .yarn/versions/75172f8d.yml
- packages/react/accessible-icon/src/AccessibleIcon.tsx
- packages/react/accordion/src/Accordion.tsx
- packages/react/alert-dialog/src/AlertDialog.tsx
- packages/react/popper/src/Popper.tsx
- packages/react/toolbar/src/Toolbar.tsx
- packages/react/tooltip/src/Tooltip.tsx
> Fix potential type definition conflicts

- .yarn/versions/4a9458c3.yml
- packages/react/presence/src/Presence.stories.tsx
- packages/react/presence/src/Presence.tsx
Bit of an oversight here 🙈  
Took me a while to figure this all out but ended up being a few simple changes in the end.
Fixes #568.
> [Presence] Add support for multiple animations

- .yarn/versions/837b9b37.yml
- packages/react/accordion/src/Accordion.test.tsx
- packages/react/accordion/src/Accordion.tsx
> [Accordion] Fix issue when closing item in single controlled accordion

- .yarn/versions/4e670816.yml
- packages/react/popover/package.json
- packages/react/popover/src/Popover.tsx
- yarn.lock
Noticed this whilst reviewing the `HoverCard` PR, I think it was a leftover from the PRs we merged yesterday.
> [Popover] Remove unused dependency

- .yarn/versions/0b0ff058.yml
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/radio-group/src/Radio.tsx
- packages/react/slider/src/Slider.tsx
- packages/react/switch/src/Switch.tsx
> [Checkbox][RadioGroup][Slider][Switch] Replace input `hidden` attribute with inline style

- .yarn/versions/0362c835.yml
- release-process.md
Was discussing this with @benoitgrelard earlier and thought it would be useful to have them documented.
> Document release process

- .yarn/versions/394b35d6.yml
- packages/react/menu/src/Menu.tsx
> [DropdownMenu] Prevent scroll when selecting item with space

- .yarn/versions/6423be2b.yml
- packages/react/id/README.md
- packages/react/polymorphic/README.md
Updates both @radix-ui/react-id & @radix-ui/react-polymorphic READMEs.
To ensure these utilities are correctly documented as public and that they have a link to their respective docs page.
> Update @radix-ui/react-[id|polymorphic] READMEs

- .yarn/versions/4c0325da.yml
- packages/react/focus-scope/src/FocusScope.tsx
> [FocusScope] Fix type definition issues

- .yarn/versions/182ce164.yml
- README.md
- packages/react/slot/package.json
- packages/react/slot/src/Slot.tsx
- yarn.lock
> [Slot] Fix slot events composition

- .yarn/versions/0741e5bb.yml
- packages/react/checkbox/package.json
- packages/react/checkbox/src/Checkbox.stories.tsx
- packages/react/checkbox/src/Checkbox.test.tsx
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/radio-group/package.json
- packages/react/radio-group/src/Radio.tsx
- packages/react/radio-group/src/RadioGroup.stories.tsx
- packages/react/switch/package.json
- packages/react/switch/src/Switch.stories.tsx
- packages/react/switch/src/Switch.tsx
- scripts/setup-tests.ts
- yarn.lock
Fixes https://github.com/radix-ui/primitives/issues/649
| Chrome | Brave | Safari | Firefox | Edge |
| - | - | - | - | - |
| ![image](https://user-images.githubusercontent.com/175330/117997139-a3a66c00-b33a-11eb-9340-3768b377253c.png) | ![image](https://user-images.githubusercontent.com/175330/117993267-7ad0a780-b337-11eb-957c-2ecdee526365.png) | ![image](https://user-images.githubusercontent.com/175330/117993307-845a0f80-b337-11eb-8a8a-1492ae8ca670.png) | ![image](https://user-images.githubusercontent.com/175330/117993347-8f14a480-b337-11eb-9bc0-c54645482941.png) | ![image](https://user-images.githubusercontent.com/175330/117994782-af912e80-b338-11eb-9d09-b2dec4295101.png) |
| iOS Portrait | iOS Landscape |
| - | - |
| ![image](https://user-images.githubusercontent.com/175330/117997783-32 …
> [Checkbox][Switch][RadioGroup] Fix native form validation

- .yarn/versions/ae6da866.yml
- packages/react/tabs/src/Tabs.stories.tsx
- packages/react/tabs/src/Tabs.tsx
In line with the changes made in #651 
- Rename `Tabs.Tab` to `Tabs.Trigger`
- Rename `Tabs.Panel` to `Tabs.Content`
cc @peduarte
> [Tabs] Rename parts 🔥 

- packages/react/menu/src/Menu.tsx
See https://github.com/radix-ui/primitives/pull/682#issuecomment-860507424
> [ContextMenu][DropdownMenu] Fix menu focus after pointer interaction

- packages/react/menu/src/Menu.tsx
This PR fixes some issues with touch events (see #682 or below) by being more explicit about how we handle specifically touch vs. mouse using pointer events.
> With touch inputs there is some odd behaviour when layered click targets overlap e.g. after a collision adjustment (seen on IOS but can reproduce in emulated dev tool)
https://user-images.githubusercontent.com/11708259/121864338-b4108480-ccf4-11eb-8e7d-c914ae84de56.mp4
> [ContextMenu][DropdownMenu] Improve touch/mouse handling separation

- .yarn/versions/ca641ce6.yml
- packages/react/slider/src/Slider.tsx
> [Slider] Fix key binding issue

- .yarn/versions/8f41e580.yml
- packages/react/scroll-area/src/ScrollArea.stories.tsx
- packages/react/scroll-area/src/ScrollArea.tsx
> [ScrollArea] Add `data-orientation` to `Scrollbar`

- .yarn/versions/188d81f2.yml
- packages/react/accordion/src/Accordion.tsx
Tiny thing I saw whilst fixing #721
> [Accordion] Add missing `React.useCallback`

- .yarn/versions/8a44e306.yml
- packages/react/roving-focus/src/RovingFocusGroup.tsx
> [RovingFocusGroup] Fix Safari issues

- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/focus-scope/src/FocusScope.stories.tsx
- packages/react/focus-scope/src/FocusScope.test.tsx
- packages/react/focus-scope/src/FocusScope.tsx
This is the first one of a stack of PRs (#700) to bring in new modality changes.
>Note: base branch is `modality` (#700), not `main`.
> [FocusScope] Update API for modality changes

- README.md
Tiny PR to fix primitive website docs. The current one is redirecting to 404
> docs: fix primitives docs URL

- .yarn/versions/6a494560.yml
- README.md
> Fix primitives docs URL

- packages/react/dialog/src/Dialog.tsx
Fixes toggle on close issue described https://github.com/radix-ui/primitives/pull/751#pullrequestreview-694816395
> [Dialog] Fix non modal toggle on close

- packages/react/alert-dialog/src/AlertDialog.tsx
See https://github.com/radix-ui/primitives/pull/758#discussion_r662357477
> [AlertDialog] Don't compose onPointerDownOutside

- .yarn/versions/5b5885a9.yml
- packages/react/dialog/src/Dialog.tsx
- packages/react/focus-scope/src/FocusScope.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
> [Popover] Explicitly focus trigger on unmount

- .yarn/versions/27156096.yml
- cypress/integration/ContextMenu.spec.ts
- packages/react/context-menu/src/ContextMenu.stories.tsx
Sibling PR to https://github.com/radix-ui/primitives/pull/744 that tests the same submenu behaviour but for `ContextMenu`.
> [ContextMenu] Add submenu int tests

- .yarn/versions/a315b7b4.yml
- packages/react/scroll-area/src/ScrollArea.tsx
I added `Presence` but forgot to add the attributes for CSS animations 🙈
> [ScrollArea] Add `data-state` to `Scrollbar`

- .yarn/versions/a593e943.yml
- ssr-testing/pages/_app.tsx
- ssr-testing/pages/accordion.tsx
- ssr-testing/pages/collapsible.tsx
- ssr-testing/pages/index.tsx
- ssr-testing/pages/scroll-area.tsx
- ssr-testing/pages/slider.tsx
- ssr-testing/pages/tabs.tsx
I noticed our SSR testing app was a little outdated while using it to test some changes.
This PR simply updates some outdated primitive apis and adds the slider to the `ssr-testing` app.
> Update SSR testbed

- .yarn/versions/7755cda3.yml
- release-process.md
I know it's obvious but I think docs are better when they make no assumptions.
> Update release process doc

- .yarn/versions/1fc120c7.yml
- packages/react/presence/src/Presence.stories.tsx
- packages/react/presence/src/Presence.tsx
I'm still struggling with some `Toast` animation bits which I'll continue to try solve separately but this at least fixes #635 for the timebeing.
> [Presence] Allow close animation only

- .github/workflows/publish-rc.yml
- .yarn/versions/6b4dcb3f.yml
~I'm not sure how to test this 😅~
~I've added links in the comments to examples I've followed so hopefully it's all good but what do we think we should do here?~
~I found [something called `act` for testing GitHub actions](https://github.com/nektos/act)  and installed Docker like it suggests but then it dawned on me that it would probably still do a publish...? so dno. I also couldn't get it to work off the bat so would require a dedicated effort.~
------------------
All tested and working smoothly when I tested with tokens that I had created. Tokens have since been switched to Stephen's which should be fine too as I've walked through correct configuration with him.
> Add GH action to publish RC on merge

- .yarn/versions/0a2f9065.yml
- packages/react/slider/src/Slider.stories.tsx
- packages/react/slider/src/Slider.tsx
Fixes #865
I've added a Chromatic regression test for it too.
> [Slider] Fix zero values issue

- .yarn/versions/03a3e321.yml
- packages/react/tabs/src/Tabs.tsx
Following up on this discussion https://github.com/radix-ui/primitives/discussions/855#discussioncomment-1316094
Closes #813.
Adding this change for discussion.
> [Tabs] Unmount content when inactive

- .yarn/versions/7e801f7f.yml
- packages/react/accordion/src/Accordion.tsx
- packages/react/alert-dialog/src/AlertDialog.tsx
- packages/react/collection/package.json
- packages/react/collection/src/Collection.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/context/src/createContext.tsx
- packages/react/dialog/src/Dialog.tsx
- packages/react/dismissable-layer/package.json
- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/id/package.json
- packages/react/id/src/id.tsx
- packages/react/label/package.json
- packages/react/label/src/Label.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/slider/src/Slider.tsx
- yarn.lock
As discussed, replaces `React.createContext` instances with our utility in preparation for the bug fixes coming for:
- #681
- #848
- #210
> [All] Replace `React.createContext` with our `createContext` util

- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.tsx
- packages/react/collapsible/src/Collapsible.stories.tsx
- packages/react/collapsible/src/Collapsible.tsx
This PR adds a `--radix-collapsible-content-width` CSS custom property to the Collapsible component.
> [Collapsible][Accordion] Add content-width CSS custom property

- .yarn/versions/a919f8ac.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.tsx
- packages/react/collapsible/src/Collapsible.stories.tsx
- packages/react/collapsible/src/Collapsible.tsx
PR from @imtiazmangerah https://github.com/radix-ui/primitives/pull/879 to run Chromatic tests.
> [Collapsible][Accordion] Add content-width CSS custom property (#879)

- .yarn/versions/d7cf46af.yml
- packages/react/dropdown-menu/src/DropdownMenu.tsx
> [DropdownMenu] Make sure a disabled trigger doesn't open

- .yarn/versions/d9afb4ce.yml
- packages/react/radio-group/src/RadioGroup.stories.tsx
- packages/react/radio-group/src/RadioGroup.tsx
Fixes #938 
-------------
Easier to review with hidden whitespace changes
-------------
> [RadioGroup] Prevent radio activation on manual focus

- packages/react/tabs/src/Tabs.tsx
updating comment to keep the standard of the other comments :D
> [Tabs] Prop comment consistency

- .yarn/versions/9ec69a56.yml
- packages/react/focus-scope/src/FocusScope.tsx
- packages/react/hover-card/package.json
- packages/react/hover-card/src/HoverCard.stories.tsx
- packages/react/hover-card/src/HoverCard.tsx
- yarn.lock
Fixes #920.
I've also added a change to `FocusScope` here to discuss. The change prevents auto focusing anchors when content opens. It feels like this isn't really the intended behaviour in most cases but need you guys to put me in line here if there is good reason to include anchors.
https://user-images.githubusercontent.com/175330/138120932-7b8a7c5a-3618-473a-89f7-74e072025245.mp4
> [HoverCard] Add DismissableLayer

- .yarn/versions/5ad189b9.yml
- packages/react/accordion/src/Accordion.tsx
See https://github.com/radix-ui/primitives/pull/959
Closes https://github.com/radix-ui/primitives/issues/958
> [Accordion] Patch for TypeError on mismatched prop types

- .yarn/versions/5e24a8c6.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/collapsible/src/Collapsible.stories.tsx
- packages/react/collapsible/src/Collapsible.tsx
Addresses these discussions 
- https://github.com/radix-ui/primitives/discussions/934
- https://github.com/radix-ui/primitives/discussions/976
-------------------
Easier to review with hidden whitespace changes
-------------------
> [Collapsible][Accordion] Disable animation when open on mount

- .yarn/versions/9b9ddfc8.yml
- packages/react/portal/src/Portal.tsx
Fixes an small issue with displayName in UnstablePortal. re: https://github.com/radix-ui/primitives/pull/936#discussion_r746709032
> [Portal] Fix UnstablePortal.displayName

- .yarn/versions/8c144add.yml
- packages/react/tooltip/src/Tooltip.stories.tsx
- packages/react/tooltip/src/Tooltip.tsx
Fixes #1001 
I mentioned on that ticket that I would look into this as part of the tooltip work.
> [Tooltip] Fix trigger when another tooltip overlays it

- .yarn/versions/89f5d350.yml
- packages/react/tooltip/src/Tooltip.tsx
**BEFORE**
https://user-images.githubusercontent.com/175330/145625502-12a1c6b1-5e28-47f9-8847-75e0526fc0f5.mp4
**AFTER**
https://user-images.githubusercontent.com/175330/145625426-c2c01782-f02d-496f-9e49-e7d4b51ef44d.mp4
> [Tooltip] Fix skip delay when re-activating focused tooltip

- .yarn/versions/8d957588.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/collapsible/src/Collapsible.tsx
> [Collapsible][Accordion] Fix controlled content animation

- .yarn/versions/d6f53453.yml
- packages/react/id/src/id.tsx
- packages/react/primitive/src/Primitive.tsx
Preventing these from logging in production environments.
> [Id][Primitive] Deprecation warnings in dev mode only

- .yarn/versions/7b453761.yml
- packages/react/collapsible/src/Collapsible.tsx
- packages/react/toolbar/src/Toolbar.tsx
> [Collapsible][Accordion] Add type attribute to accordion button

- .yarn/versions/af274a19.yml
- packages/react/menu/src/Menu.tsx
> [DropdownMenu] Stop menu from preventing tab keypress

- .yarn/versions/64b075dd.yml
- packages/react/toggle-group/src/ToggleGroup.tsx
> [ToggleGroup] Use radio role for single toggle group

- .yarn/versions/3cecd9fd.yml
- packages/react/toolbar/src/Toolbar.tsx
> [Toolbar] Fix missing display name

- .yarn/versions/1a8b8a1b.yml
- cypress/integration/ContextMenu.spec.ts
- cypress/integration/DropdownMenu.spec.ts
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/menu/src/Menu.tsx
Closes #1139
I was about to write up a response to the latest comments on the ticket but had an idea which should solve this without getting into another perf discussion.
> [DropdownMenu][ContextMenu] Bind keyboard checks only when necessary

- packages/react/navigation-menu/src/NavigationMenu.tsx
The "basic" usage of the content (without viewport) had an issue where if you animated the content and tabbed quickly enough after dismissing, you'd lose focus. This is because the content is still in tab order during its transitional exit.
https://user-images.githubusercontent.com/11708259/155197388-ac14a1e3-37d4-4dab-a5c4-6be782578486.mp4
To solve this we unify the tab management for viewport and non viewport variants so that they both benefit from tab removal.
> [NavigationMenu] Avoid focus loss without viewport

- .yarn/versions/9c034a97.yml
- packages/react/toast/src/Toast.stories.tsx
- packages/react/toast/src/Toast.tsx
> [Toast] Fix toast reopen timer during animation

- .yarn/versions/00368f6c.yml
- packages/react/select/src/Select.tsx
- packages/react/use-body-pointer-events/src/useBodyPointerEvents.tsx
> [Select] Fix compatibility with React > 16.8

- .yarn/versions/f88dfd51.yml
- packages/react/select/src/Select.tsx
> [Select] Fix position issue with Content padding

- .yarn/versions/efafef3a.yml
- packages/react/toast/src/Toast.stories.tsx
- packages/react/toast/src/Toast.tsx
> [Toast] Fix MutationObserver on key change

- .yarn/versions/16a4360b.yml
- packages/react/scroll-area/src/ScrollArea.tsx
Noticed that this wasn't being cleaned up.
> [ScrollArea] Cleanup setState unmount warning

- .storybook/main.js
- .yarn/versions/00fae535.yml
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
> [Select] Fix alignment issues

- .storybook/main.js
- .yarn/versions/00fae535.yml
- package.json
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
- yarn.lock
> [Select] Add chromatic stories

- .yarn/versions/0ca5f5ea.yml
- packages/react/scroll-area/src/ScrollArea.stories.tsx
- packages/react/scroll-area/src/ScrollArea.tsx
Added `Presence` to `ScrollThumb`. Closes https://github.com/radix-ui/primitives/issues/1050
> [ScrollArea] Add `Presence` to `ScrollThumb`

- .yarn/versions/eb4bb742.yml
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
closes https://github.com/radix-ui/primitives/issues/1021
Might be better to review after merging https://github.com/radix-ui/primitives/pull/1394
> [ContextMenu][DropdownMenu][Popover] Move `allowPinchZoom` to `Root`

- .yarn/versions/c0845573.yml
- packages/react/dialog/package.json
- packages/react/dismissable-layer/package.json
- packages/react/menu/package.json
- packages/react/popover/package.json
- packages/react/select/package.json
- yarn.lock
Patched in https://github.com/theKashey/react-remove-scroll-bar/pull/32
> Resolve react-remove-scroll offset regression

- .yarn/versions/b3a012d8.yml
- packages/react/dialog/package.json
- packages/react/dismissable-layer/package.json
- packages/react/menu/package.json
- packages/react/popover/package.json
- packages/react/select/package.json
- yarn.lock
Fixes https://github.com/radix-ui/primitives/issues/1417
> [Dialog][Popover][DropdownMenu][ContextMenu][Select] Upgrade react-remove-scroll

- .yarn/versions/baedf443.yml
- packages/react/toast/src/Toast.tsx
https://github.com/radix-ui/primitives/pull/1528#discussion_r927586168
> [Toast] Announce as status rather than group

- .yarn/versions/f8fa5d29.yml
- packages/react/slider/src/Slider.stories.tsx
- packages/react/slider/src/Slider.tsx
> [Slider] Allow visual inversion

- .yarn/versions/a263f870.yml
- packages/react/slider/src/Slider.stories.tsx
- packages/react/slider/src/Slider.tsx
> [Slider] Add `onValueCommit` for discrete value changes

- .yarn/versions/3d5a002d.yml
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
Follow up from https://github.com/radix-ui/primitives/pull/1598#discussion_r992348472
Related: #1598
> [Select] Ensure `required` works correctly

- .yarn/versions/be773afe.yml
- yarn.lock
See https://github.com/radix-ui/primitives/discussions/1594#discussioncomment-3913318 and https://github.com/theKashey/react-remove-scroll-bar/issues/35#issuecomment-1276809669
> Resolve dev console `scrollbar size calculation` warning

- .yarn/versions/fda33d6a.yml
- packages/react/scroll-area/src/ScrollArea.tsx
- packages/react/toast/src/Toast.tsx
As discussed in https://github.com/radix-ui/primitives/pull/1753#issuecomment-1302047373
> Standardize checking for pointer capture before releasing

- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/menubar/package.json
- packages/react/menubar/src/Menubar.stories.tsx
- packages/react/menubar/src/Menubar.tsx
- packages/react/roving-focus/src/RovingFocusGroup.tsx
- yarn.lock
- Add keyboard controls
- Add RTL support
- Tabbing is not possible yet per our other menu implementations
https://user-images.githubusercontent.com/11708259/208924409-4158de06-1974-4e5a-917b-18859ea6b583.mp4
> [Menubar] Improve keyboard controls

- packages/react/menubar/src/Menubar.stories.tsx
- packages/react/menubar/src/Menubar.tsx
- Provides a default for `align` that matches a typical `MenuBar` presentation
> [MenuBar] Provide appropriate position defaults

- cypress/integration/Menubar.spec.ts
- packages/react/menubar/src/Menubar.stories.tsx
Add Cypress and Chromatic tests
> [MenuBar] Add Cypress and Chromatic tests

- .yarn/versions/fa513961.yml
- packages/react/accordion/package.json
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.test.tsx
- packages/react/accordion/src/Accordion.tsx
- yarn.lock
Resolves https://github.com/radix-ui/primitives/issues/881
> [Accordion] Add `orientation` prop to support horizontal orientation

- .yarn/versions/01e3ca82.yml
- packages/react/navigation-menu/src/NavigationMenu.tsx
> [NavigationMenu] Do not close when metaKey is down

- .yarn/versions/ca8a29d8.yml
- packages/react/dialog/src/Dialog.tsx
- packages/react/popover/src/Popover.tsx
> [Popover] Fix close/re-open bug on Safari

- packages/react/toggle/src/Toggle.test.tsx
- chore(toggle): Add unit tests
Why did I add tests? Toggle is a simple component, yet a great real-world example for devs starting to learn A11Y and how to use unit tests to cover A11Y attributes in their components. I'll use this as an example for an A11Y workshop I'm conducting.
> [Toggle]: Add unit tests

- .yarn/versions/96d1204b.yml
- cypress/integration/Select.spec.ts
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
> [Select] Use `""` `value` to reset to placeholder

- .github/CONTRIBUTING.md
- .yarn/versions/a66e1aa5.yml
Hi, i found small wrong link in documentaion so i try to fix it
> Fix issue link in contribution guide

- .yarn/versions/9471cb0c.yml
- packages/react/scroll-area/src/ScrollArea.tsx
> [ScrollArea] Fix types

- .yarn/versions/efa9f1f5.yml
- packages/react/dialog/package.json
- packages/react/dismissable-layer/package.json
- packages/react/menu/package.json
- packages/react/popover/package.json
- packages/react/select/package.json
- yarn.lock
> Upgrade react-remove-scroll version

- .yarn/versions/b20a66e3.yml
- packages/react/slider/src/Slider.stories.tsx
- packages/react/slider/src/Slider.tsx
> [Slider] Add ability to name each thumb for more flexibility

- .yarn/versions/8ac79743.yml
- packages/react/portal/package.json
- yarn.lock
`@radix-ui/react-portal` imports from `packages/react/portal/src/Portal.tsx`, but does not declare a dependency on `@radix-ui/react-use-layout-effect` in its `package.json`.
> Add missing dependency to `@radix-ui/react-portal` 

- .yarn/versions/1c5efa6d.yml
- packages/react/scroll-area/src/ScrollArea.tsx
This link was dead, [updating](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#description) to the current.
> Fix URL link in code comment

- packages/react/dialog/src/Dialog.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/primitive/src/Primitive.tsx
- packages/react/select/src/Select.tsx
- packages/react/slider/src/Slider.tsx
- packages/react/toast/src/Toast.stories.tsx
> chore: fix some comments

- release-process.md
fix broken change log link in `release-process.md`. 👇 
https://github.com/radix-ui/primitives/assets/48552260/06ffbe79-c4a9-40e2-9aef-c8799665a41c
> Fix broken change log link

- packages/react/tooltip/src/Tooltip.test.tsx
Added some unit tests for the tooltip component. No changes or updates to functionality.
> test: (@radix-ui/react-tooltip) add unit tests for tooltip component 

- packages/react/scroll-area/README.md
Hi! Just noticed this link was incorrect and 404s 🙂 
s/scrollbar/scroll-area does the trick
> Update scroll-area component docs link in README

- packages/react/scroll-area/README.md
update the document address of scroll-area
> docs: update the document address of scroll-area

- packages/react/compose-refs/src/composeRefs.tsx
This is a follow up to #3283 to remove an error from logs in React <19.
> Avoid error in logs on React <19 when using composeRefs

- packages/react/one-time-password-field/src/one-time-password-field.stories.tsx
> auth component tests + stories

- .github/workflows/build.yml
* enable `pnpm` caching in `actions/setup-node`
> ci(.github/workflows/build.yml): enable 'pnpm' caching in 'actions/setup-node'

- .changeset/wet-otters-hang.md
- apps/ssr-testing/app/layout.tsx
- apps/ssr-testing/app/password-toggle-field/page.tsx
- apps/storybook/package.json
- apps/storybook/stories/password-toggle-field.stories.module.css
- apps/storybook/stories/password-toggle-field.stories.tsx
- packages/react/password-toggle-field/README.md
- packages/react/password-toggle-field/eslint.config.mjs
- packages/react/password-toggle-field/package.json
- packages/react/password-toggle-field/src/index.ts
- packages/react/password-toggle-field/src/password-toggle-field.test.tsx
- packages/react/password-toggle-field/src/password-toggle-field.tsx
- packages/react/password-toggle-field/tsconfig.json
- packages/react/radix-ui/package.json
- packages/react/radix-ui/src/index.ts
- pnpm-lock.yaml
> Add new `PasswordToggleField` primitive

- .changeset/sad-colts-train.md
- packages/react/checkbox/src/checkbox.tsx
Fixes https://github.com/radix-ui/primitives/issues/3527
> Fix type error emitted in build artifacts

- packages/react/slot/src/slot.test.tsx
* This includes the changes from #3477, which was merged while #3426 was still in progress.
> test(react/slot): replace deprecated 'ElementRef' with 'ComponentRef'
