- .yarn/versions/fc718974.yml
- packages/react/checkbox/src/Checkbox.stories.tsx
- packages/react/presence/src/Presence.tsx
This work all stemmed from an issue with `Checkbox` indeterminate state in our stories. There was a FOUC during its indicator unmount phase due to these `requestAnimationFrame`s in `Presence` and the fact that our `Checkbox` stories assume "unmounted" means "unchecked". 
I've updated the story to more explicitly target states for styles as I don't think it's a good idea to assume that when it is not `indeterminate` it is unmounted or `checked`. A new state could be added so the logic should be more explicit. Plus, "unchecked" and "unmounted" are conceptually different things that could happen at different times (like this).
This PR:
- Reduces the amount of logic wrapped in `requestAnimationFrame` to try ease these sorts of issues. I want to try remove/improve the one around the …
> [react-presence]: Reduce `requestAnimationFrame` logic

- .yarn/versions/a6bd4f3f.yml
- packages/core/popper/src/popper.stories.tsx
- packages/core/popper/src/popper.ts
- packages/core/utils/src/geometry.ts
- packages/react/popper/src/Popper.tsx
Closes #350
We had an implicit dependency on `window.innerWidth` and `window.innerHeight` but our popper wasn't reacting to changes in window size.
This PR adds a more explicit relationship down to the low-level popper utility.
It doesn't have any impact on any public APIs.
> [Popper] Add window size explicit dependency

- .yarn/versions/257b7174.yml
- packages/react/scroll-area/src/ScrollArea.stories.tsx
- packages/react/scroll-area/src/ScrollArea.tsx
This PR exports a wrapper component that will bypass the double render caused by our `ScrollArea` implementation. This is intended as a stop-gap solution to an issue @StephenHaney is having with internal event listeners not running because we throw away the initially rendered DOM.
Long term I'm leaning towards removing the native fallback altogether and exposing a hook to detect compatibility instead, leaving it to the consumer to handle feature detection so they can wrap it however they'd like. That would let us get rid of the weird ref issues in the simplest way IMO. I'd like to wait for @jjenzz to get back to review and offer feedback as well.
> ScrollArea: Temporary workaround for double render (#351)

- package.json
Just removing an unnecessary `@types/styled-system__core` resolution in the package.json. This has been there since the first days of Radix but that dependency is no longer used by the project itself or any sub-dependency. Everything seems to work fine after deleting it.
> Remove unnecessary package resolutions

- .yarn/versions/f17394b2.yml
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.stories.tsx
- packages/react/popover/src/Popover.tsx
I finally managed to fix this one! 🎉 
This was an issue that was reported by Lucas with regards to the `DropdownMenu`.
He was trying to turn off `disableOutsidePointerEvents` on `DropdownMenu.Content` so you can click through to things, and although it did work (for example button actions would be called), it wouldn't let him focus inside an input straight up.
I was sure I made this work with all the work I did on `DismissableLayer` and `FocusScope`, I even had some stories.
After reviewing this all with him, I realised that we had the same problem in `Popover` too.
But then I could see that my stories in `DismissableLayer.stories` which cover this specifically were working fine…
> **NOTE**: we have fake `Dialog` and fake `Popover` in this story file (basically crude versions of them to …
> [Popover][DropdownMenu] Fix race condition when dismissing via click outside and `disableOutsidePointerEvents` is off. 

- .yarn/versions/77e1fa7a.yml
- packages/react/accordion/src/Accordion.test.tsx
- packages/react/accordion/src/Accordion.tsx
This was raised on Discord.
If the `Accordion.Root` had `disabled={false}`, the `Accordion.Item`s would all be enabled regardless of whether they explicitly had a `disabled={true}` prop themselves.
> [react-accordion] Allow disabled `AccordionItem` when `Accordion` is `disabled={false}`

- .yarn/versions/e7611a1d.yml
- packages/react/dialog/src/Dialog.tsx
I've spotted a small regression with `Dialog` 0.0.2 (and therefore `AlertDialog)` (closing when tabbing even though focus is trapped).
It was introduced introduced after we made the changes in `FocusScope` to not cancel out `focusout` event.
We had made the necessary changes in `Popover` and `Menu`, etc (to `preventDefault` when `trapFocus` was true) but forgot to do it always in the case of `Dialog` because focus is always trapped.
> [Dialog][AlertDialog] Fix regression

- .yarn/versions/c778bbee.yml
- packages/react/menu/src/Menu.tsx
Closes #402 
After checking a reported issue #402, I realised we have introduced a bug in dependents of `Menu` (`ContextMenu`, `DropdownMenu`) when we added the `selector` prop.
This is because the expectation on what attributes are present changed, and we didn't account for it here.
Namely, before we were expecting the `data-radix-menu-item` to be present even in dependents of `Menu`.
This is no longer a safe assumption to make obviously, therefore we cannot rely on this selector.
Looking at other places we build selectors like this (roving focus behaviour, or typeahead behaviour) they both add their own data attribute to ensure they can safely select items. So it seems in this case we should be doing the same somehow. It feels a bit more annoying given that we know there is already a …
> [ContextMenu][DropdownMenu] Fix issue introduced by new `selector` prop

- .yarn/versions/ef0bd797.yml
- packages/react/accordion/src/Accordion.tsx
- packages/react/alert-dialog/src/AlertDialog.tsx
- packages/react/announce/src/Announce.tsx
- packages/react/arrow/src/Arrow.tsx
- packages/react/aspect-ratio/src/AspectRatio.tsx
- packages/react/avatar/src/Avatar.tsx
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/collapsible/src/Collapsible.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dialog/src/Dialog.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/label/src/Label.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/popper/src/Popper.tsx
- packages/react/progress/src/Progress.tsx
- packages/react/radio-group/src/Radio.tsx
- packages/react/radio-group/src/RadioGroup.tsx
- packages/react/scroll-area/src/ScrollArea.tsx
- packages/react/separator/src/Separator.tsx
- packages/react/slider/src/Slider.tsx
- packages/react/switch/src/Switch.tsx
- packages/react/tabs/src/Tabs.tsx
- packages/react/toggle-button/src/ToggleButton.tsx
- packages/react/tooltip/src/Tooltip.tsx
- packages/react/utils/src/extendComponent.tsx
- packages/react/visually-hidden/src/VisuallyHidden.tsx
We noticed that Stitches passes an explicit `as={undefined}` prop to our components which wipes them out. We've decided that this shouldn't be possible and to explicitly handle this case by always falling back to a default.
We're going to make sure all our other defaults are handled correctly in a separate PR to avoid similar situations like this in future.
> Explicitly declare default values for `as` and `selector` props

- .yarn/versions/8ca9debf.yml
- packages/react/portal/package.json
- packages/react/portal/src/Portal.stories.tsx
- packages/react/portal/src/Portal.test.tsx
- packages/react/portal/src/Portal.tsx
- yarn.lock
If the `Portal` is injected in `body` (default behaviour), we will now assume we want whatever is portalled to appear on top of everything.
Ideally this would be handled by making sure the app root creates a new stacking context, however this is quite hard to automate and we have had many users getting tripped up by this already (see #368, https://github.com/modulz/composer/pull/97 for example).
For this reason, we have opted for setting the max z-index on the portal itself in such cases.
Also, standardizes the portal element to follow the usual convention of other primitives, with regards to as, types and selector.
> 🔥 NOTE: This is a potential breaking change as the element rendered used to be `<radix-portal>` and will now be `<div data-radix-portal>`
> [Portal] Fix potential out of the box layering issues

- .yarn/versions/c0ee0213.yml
- packages/core/popper/src/popper.ts
We noticed an issue with Popover flashing (sliding) when positioning.
This was due to the changes we made to `Portal` adding styles to position above things.
The main issue is that now we have 2 parents with `position: absolute` and so intrinsic-sized elements would collapse. 
> Update: we've now made a more surgical fix in popper itself.
> [Popper] Fix collapsing layout issues

- .yarn/versions/4cd277fa.yml
- packages/react/polymorphic/src/forwardRefWithAs.test.tsx
- packages/react/polymorphic/src/forwardRefWithAs.ts
Although all of our polymorphic type tests are passing, we don't know of a way to test the autocompletion element of TS and Pedro spotted that it wasn't working.
This PR fixes autocomplete:
https://user-images.githubusercontent.com/175330/106663246-58422c00-659b-11eb-86db-9dca344ca261.mov
> [Polymorphic] Fix type autocompletion for polymorphic components

- .yarn/versions/3cd46ef0.yml
- packages/react/dialog/src/Dialog.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
Closes #419
Because of the fact some of our components use `Presence` to ensure animating on unmount can be done, unmounting is actually potentially delayed by a couple frames.
This could cause our `FocusScope` unmount focus event to be trapped even though we've actually already closed the component (Dialog, Popover, Menu, etc).
For some reason, it sent Chrome into a weird state in these conditions which meant nothing was really focused (even though it reports `document.activeElement === document.body`…).
> [Dialog][Popover][Menu] Prevent delayed trapping

- .yarn/versions/199e942a.yml
- package.json
It has been bugging us that the version check always trips us up but we only find out it's an issue during CI. This will hopefully catch this issue sooner before we switch to different tasks!
> Add version check to pre-push

- .yarn/versions/bca7fd53.yml
- packages/react/radio-group/src/RadioGroup.tsx
It didn't make sense to expect the `name` to be passed to each item when they should all be the same in a group.
> [RadioGroup] Move `name` prop from `RadioGroupItem` to `RadioGroup`

- .yarn/versions/5499fbcf.yml
- packages/react/checkbox/src/Checkbox.test.tsx
- packages/react/presence/src/Presence.tsx
Closes #416 .
I've had to bite the bullet here and delay mount to. Tbh, it actually makes sense that `Presence` would ensure mount and unmount happen in the same frame. 
I can't think of a reason why delaying the mount by a frame will cause any issues but let me know if you can.
> [Accordion] Fix open/close flicker

- .github/workflows/chromatic.yml
- .yarn/versions/82b83501.yml
- packages/react/accordion/src/Accordion.stories.tsx
Adding `--exit-once-uploaded` and `--exit-zero-on-changes` flags to improve github action speed.
> Add flag to improve Chromatic action speed

- .yarn/versions/c771aa44.yml
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
cc @vladmoroz, this should help you resolve your focus troubles once we release new versions.
> [DropdownMenu][ContextMenu] Expose `onCloseAutoFocus`

- .github/workflows/chromatic.yml
- .yarn/versions/b232b1ff.yml
We need these apparently. This will consume our screenshot quota quite a bit more but I've started the OSS project process with Chromatic team as we can apparently have an increased quota this way 🤞
> Chromatic build for `main` pushes

- .yarn/versions/fbaf02d6.yml
- README.md
Chromatic team are switching us to the OSS plan and have asked if we could mention them to help other OSS projects find them.
This is us kindly obliging 😛
> Add Chromatic thanks

- .yarn/versions/0014e767.yml
- packages/react/slider/src/Slider.stories.tsx
- packages/react/slider/src/Slider.tsx
Closes #462
@jjenzz this is what you get if you pass `step={0}` and try and move it:
- it won't move
- the value becomes `NaN`
I think that's fine personally. It's pretty obvious it shouldn't work if you say that it goes by increments of `0`.
> [Slider] Fix step rounding issue

- .yarn/versions/99ff61ba.yml
- packages/react/presence/package.json
- packages/react/presence/src/Presence.tsx
- packages/react/presence/src/useStateMachine.tsx
- yarn.lock
---------------
ℹ️&nbsp;&nbsp;Easier to review with hidden whitespace changes.
---------------
We had report of some perf issues with nested `Collapsible`s and I realised `Presence` was causing some problems there. 
I've prevented some `useEffect` logic from running unnecessarily on mount and removed `@xstate/fsm`. 
I had noticed that `@xstate/fsm` really eagerly re-renders components during my Carousel work so we can probably do without that and the additional bundle size it adds for such a simple machine here.
These changes managed to **double** the speed in my tests.
> [Presence] Improve `Presence` perf

- .yarn/versions/e9bd31b7.yml
- packages/react/accordion/src/Accordion.tsx
- packages/react/utils/src/createContext.tsx
Before our `Carousel` call earlier, I started applying this across our codebase. I'll PR each component in separate PRs.
> Update `createContext` to expose a Provider that accepts props

- .yarn/versions/6a723c9d.yml
- packages/react/tabs/src/Tabs.tsx
> [Tabs] Add RTL support (dir prop)

- .yarn/versions/bbcb1af3.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.test.tsx
- packages/react/accordion/src/Accordion.tsx
- Adds support for multiple values
- Toggles items by default (clicking button again will close item)
- To prevent items from closing, consumer now needs to control it
- Updates tests
- Updates stories
> [Accordion] Support multiple values

- .yarn/versions/d06510b4.yml
- packages/react/alert-dialog/src/AlertDialog.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/primitive/src/extendPrimitive.test.tsx
- packages/react/primitive/src/extendPrimitive.tsx
- packages/react/radio-group/src/RadioGroup.tsx
- packages/react/tooltip/src/Tooltip.tsx
Adds support for `defaultProps` to `extendPrimitive`. 
The plan is that with this change we could document this so that consumers can avoid the re-wrapping of types and `React.forwardRef` dance when all the need is to add a `className` or `data` attribute.
> [Primitive] Add `defaultProps` support to `extendPrimitive`

- .yarn/versions/b4dfb97b.yml
- packages/core/popper/src/popper.ts
Closes #540 
The issue is kinda intricate but I will try and give a summary here…
- For a popper to position itself it needs a few measurements (anchor react, popper size)
- Until these measurements are available, the popper needs to be measurable, but not visible, nor impact the flow/layout
- For this, we return some default styles where it is positioned fixed, out of the flow, and also had `pointer-events: none` to avoid catching any events
- That said, we can see here that some events were still caught (including hover)
- This is because `DropdownMenu` and others use `DismissableLayer` and sometimes set `disabledOutsidePointerEvents: true`
- This in turn puts `pointerEvents: 'none'` on `document.body` and `pointerEvents: 'auto'` on the content part, so in this case it puts it on what …
> [Popper] Fix potential issues with non-measured positioning

- .yarn/versions/616e0269.yml
- packages/react/toolbar/package.json
- packages/react/toolbar/src/Toolbar.stories.tsx
- packages/react/toolbar/src/Toolbar.tsx
- yarn.lock
Now that we have merged `ToggleGroup`, this replaces `ToolbarRadioGroup` with `ToolbarToggleGroup` as we have agreed the former is more apt. in the context of a toolbar.
> [Toolbar] Replace `ToolbarRadioGroup` with `ToolbarToggleGroup`

- .yarn/versions/d3072ea0.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.tsx
We moved props above spread to give consumers control but the variable here was already handling the prop value fallback. By moving it above the spread, the spread was overriding it completely because we do not destructure `disabled` from props.
```jsx
const disabled = accordionContext.disabled || props.disabled;
```
We had it the way it was because the expectation is:
- Root disabled = All items disabled
- **Root disabled with an item enabled = All items disabled**
- Root enabled = All items enabled
- Root enabled with an item disabled = Item disabled
I've updated the Chromatic stories to catch this in future.
> [Accordion] Move disabled prop after spread

- .yarn/versions/6574b316.yml
- packages/react/presence/src/Presence.tsx
While trying to fix #330, I realised that our recent change to remove `requestAnimationFrame`s in `Presence` had unmasked an issue that appears to have always been lurking within `Presence` but surfaced when we removed the rafs.
It was breaking `ContextMenu` so I've fixed this first before focusing on #330.
`Presence` would sometimes think the animation name had changed when it hadn't, or it would communicate an animation start when changing to `none` which would suspend unmount but an `animationEnd` event would never occur.
Fixes:
- Only update `prevAnimationNameRef` on `animationEnd` event because we know an animation has occurred in this case.
- If the animation name changes to `none` there is no exit animation so we `send('UNMOUNT')` instantly. This occurs in the following scenario: …
> [Presence] Fix unmount hanging

- .yarn/versions/69274a3d.yml
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dialog/src/Dialog.tsx
Closes #330
**Notes for future self**:
- The reason this solution works is because we are essentially re-enabling pointer-events quicker (as soon as `open` changes to `false`) but also very importantly because of the order of events. This is because the `open` will change from `true` to `false` when a pointer down outside event happens in our `DismissableLayer` which happens when the `mousedown` event has bubbled up all the way to the `document`. Then the `contextmenu` event on `ContextMenu.Trigger` gets handled correctly because in DOM events, `contextmenu` happens AFTER `mousedown`.
- We are assuming that `Dialog.Overlay` isn't an optional part for now. That's why we always prevent closing on right click. If this becomes an issue down the line, we can track whether the overlay part is …
> [ContextMenu] Fix conflict between opening & disabling pointer events

- .yarn/versions/317d93f0.yml
- packages/react/tooltip/src/Tooltip.stories.tsx
- packages/react/tooltip/src/Tooltip.tsx
- packages/react/tooltip/src/tooltipStateChart.tsx
----------
----------
I'll add versions file after the above is merged ☝️ 
----------
Closes #543
> [Tooltip] Add custom duration

- .yarn/versions/37a43925.yml
- packages/react/tooltip/package.json
- packages/react/tooltip/src/Tooltip.stories.tsx
- packages/react/tooltip/src/Tooltip.tsx
- yarn.lock
----------
----------
I'll add versions file after the above is merged ☝️ 
----------
Closes #459
> [Tooltip] Add unmount animation support

- .yarn/versions/917c19ff.yml
- packages/react/alert-dialog/package.json
- packages/react/context-menu/package.json
- packages/react/dialog/package.json
- packages/react/dropdown-menu/package.json
- packages/react/menu/package.json
- packages/react/popover/package.json
- packages/react/tooltip/package.json
- yarn.lock
See: https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0
Also related: https://github.com/pastelsky/bundlephobia/issues/494
> Forward missing peer dependency: `react-dom`

- .yarn/versions/418f0739.yml
- packages/react/roving-focus/src/RovingFocusGroup.tsx
Closes #584 
I've isolated just that fix so it's easier to review.
> [RovingFocusGroup] Fix `tabIndex` regression

- .yarn/versions/fd71a5b7.yml
- packages/react/alert-dialog/src/AlertDialog.stories.tsx
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/dismissable-layer/src/DismissableLayer.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.stories.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/package.json
- packages/react/popover/src/Popover.stories.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/popper/src/Popper.stories.tsx
- packages/react/popper/src/Popper.tsx
- packages/react/toolbar/src/Toolbar.stories.tsx
- packages/react/tooltip/src/Tooltip.stories.tsx
- packages/react/tooltip/src/Tooltip.tsx
- packages/react/use-rect/package.json
- packages/react/use-rect/src/useRect.tsx
- yarn.lock
--------------
ℹ️ &nbsp;&nbsp;&nbsp;Easier to review with hidden whitespace changes.
--------------
We had refs as hook dependencies which meant the hook logic would never execute if refs weren't available on mount and wouldn't re-execute if refs were re-assigned.
~This adds a new `useNode` hook that will return an up to date `node` base on a given `ref` so that the `node` can be used as the hook dependency instead.~
This PR is the first part of a wider change. This part does the following: 
- Creates a new `Anchor` part in `Popper` that will allow us to attach a callback ref internally (next PR)
- Recomposes `Anchor` in the relevant components (`Tooltip`, `DropdownMenu`, `Popover` etc.)
- 🔥 Exposes the `Anchor` from `Popover` as an optional part
- 🔥 Removes `anchorRef` capability from …
> [Popover][DropdownMenu][Tooltip] Replace or remove `anchorRef` 🔥

- .yarn/versions/54d8ec44.yml
- packages/core/popper/src/popper.stories.tsx
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/label/src/Label.tsx
- packages/react/popper/src/Popper.tsx
- packages/react/radio-group/src/Radio.tsx
- packages/react/slider/src/Slider.tsx
- packages/react/switch/src/Switch.tsx
- packages/react/tooltip/src/Tooltip.tsx
- packages/react/use-rect/src/useRect.tsx
- packages/react/use-size/src/useSize.tsx
--------------
--------------
Part 2 of the `ref` work. This PR updates our `useSize`, `useRect`, `useDirection` and `useLabelContext` hooks to receive a DOM node rather than a ref. This allows effects to re-execute if the node changes or mount is delayed.
> [Popper][Label][Slider] Update hooks to receive node

- .yarn/versions/baac8732.yml
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/radio-group/src/Radio.tsx
- packages/react/switch/src/Switch.tsx
Fix #596
> Note: Only text controls can be made read-only, since for other controls (such as checkboxes and buttons) there is no useful distinction between being read-only and being disabled, so the readonly attribute does not apply.
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly
> [Checkbox][RadioGroup][Switch] Remove `readOnly` prop 🔥 

- .yarn/versions/6a0b9aad.yml
- packages/react/context-menu/package.json
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- yarn.lock
We were missing this prop so that people can use the state to apply styles or whatever fancy stuffs they're up to 🙂
> [ContextMenu] Add `onOpenChange` callback

- .yarn/versions/51d71892.yml
- packages/react/hover-card/README.md
- packages/react/hover-card/package.json
- packages/react/hover-card/src/HoverCard.stories.tsx
- packages/react/hover-card/src/HoverCard.tsx
- packages/react/hover-card/src/index.ts
- ssr-testing/pages/hover-card.tsx
- ssr-testing/pages/index.tsx
- tsconfig.json
- yarn.lock
Closes https://github.com/radix-ui/primitives/issues/387
This PR adds the `HoverCard` primitive, [see here for discussion](https://github.com/radix-ui/primitives/issues/387).
Simple, straightforward primitive heavily based on `Popover` and `Tooltip`, intended as a contextual enhancement for links via pointer interaction, no focus management.
https://user-images.githubusercontent.com/11708259/114609510-cb9ca400-9c96-11eb-8cfd-abb5bdda506c.mov
Basic usage:
```jsx
<HoverCard>
<HoverCardTrigger href="/some-awesome-page">
Link text
</HoverCardTrigger>
<HoverCardContent>
<HoverCardArrow />
Card content
</HoverCardContent>
</HoverCard>
```
> Add `HoverCard` primitive

- .yarn/versions/0182f8a3.yml
- packages/react/alert-dialog/src/AlertDialog.tsx
- packages/react/polymorphic/src/polymorphic.test.tsx
- packages/react/polymorphic/src/polymorphic.ts
Does what it says on the 🥫 
Pedro reported an issue today with this. When trying to pass a component to the `as` prop we would lose prop autocompletion for the custom props on the passed component.
I've fiddled about with this for a while and it seems I've managed to improve perf too as an unintended side effect 😅  bonus.
I've also added some new tests for the `ref` prop to make sure that still works!
https://user-images.githubusercontent.com/175330/115457283-37918600-a21c-11eb-9445-fd6862a7da14.mov
> [Polymorphic] Improve perf and fix `as={Comp}` props

- .yarn/versions/825bad1a.yml
- packages/react/dismissable-layer/src/DismissableLayer.tsx
I ran across a case where layers unmount before `onFocusCapture` fires, causing the async state warning to throw.
This PR ensures the cleanup also happens in lifecycle.
https://user-images.githubusercontent.com/11708259/115879022-19f13600-a441-11eb-8777-01510dce1bde.mov
> [DismissableLayer] Cleanup `onFocusOutside` timer

- .yarn/versions/42082bf2.yml
- packages/core/number/src/number.ts
- packages/react/accordion/src/Accordion.tsx
- packages/react/collection/package.json
- packages/react/collection/src/Collection.stories.tsx
- packages/react/collection/src/Collection.tsx
- packages/react/menu/package.json
- packages/react/menu/src/Menu.tsx
- packages/react/radio-group/package.json
- packages/react/radio-group/src/RadioGroup.tsx
- packages/react/roving-focus/package.json
- packages/react/roving-focus/src/RovingFocusGroup.stories.tsx
- packages/react/roving-focus/src/RovingFocusGroup.tsx
- packages/react/slot/src/Slot.tsx
- packages/react/tabs/package.json
- packages/react/tabs/src/Tabs.tsx
- packages/react/toggle-group/package.json
- packages/react/toggle-group/src/ToggleGroup.tsx
- packages/react/toolbar/package.json
- packages/react/toolbar/src/Toolbar.tsx
- ssr-testing/pages/roving-focus-group.tsx
- yarn.lock
Closes #581 
---
> Note: Better view with whitespace turned off
---
This PR primarily refactors the internals of `RovingFocusGroup` so we can take into account the fact that hidden items don't get focused by the browser.
The crux of the implementation here is that we've introduced a wrapper as part of that API which will act as a proxy to send focus programatically to the correct place. We have a reference to all items in the group and so, we can programatically and progressively attempt to focus the "first" item, and eventually land on the correct one (the first visible one) without having to resort to calculating computed styles to know if an item is indeed hidden.
Once that was done, all of the dependent packages needed updated accordingly.
This has made the overall implementation(s) …
> [RovingFocusGroup] Refactor internals to take into account hidden items

- packages/core/primitive/src/primitive.tsx
- packages/react/slot/src/Slot.tsx
Right now `SlotClone` components replace child handlers (props starting with 'on') with a composed event with child handler and slot handler.
If the child handler is a custom handler that should receive more than 1 argument, it will receive only the first argument because the `composeEventHandlers` only pass the first argument to the handlers. 
With this change it will pass all received arguments to the handlers.
> [Primitive][Slot] Fix slot event composition for custom handlers

- .yarn/versions/fe0cbc34.yml
- packages/react/polymorphic/src/polymorphic.ts
Fixes #647
Replaces `React.JSXElementConstructor` with `React.ComponentType` to allow components typed by external libs in the `as` prop.
You can see the example from the issue working with this code here https://codesandbox.io/s/admiring-kalam-k2ltk?file=/src/App.tsx
> [Polymorphic] Narrow with `React.ComponentType` instead

- .yarn/versions/9969c043.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.test.tsx
- packages/react/accordion/src/Accordion.tsx
- packages/react/collapsible/src/Collapsible.stories.tsx
- packages/react/collapsible/src/Collapsible.test.tsx
- packages/react/collapsible/src/Collapsible.tsx
This PR contains a few things that came from discussing with @peduarte whilst he was writing the article for `Accordion`.
- 🐛 Omit the `type` prop on `Accordion` so it doesn't appear in the DOM
- 🔥 Rename `Collapsible.Button` to `Collapsible.Trigger`
- 🔥 Rename `Accordion.Button` to `Accordion.Trigger`
- 🔥 Rename `Accordion.Panel` to `Accordion.Content`
- 🔥 Rename `--radix-accordion-panel-height` to `--radix-accordion-content-height`
- ✨ ~**Add new `preventAllClosed` prop to `Accordion`**~
- :fire: **add new `collapsible` prop  to `<Accordion type="single">`**
Now, for a bit of context on that last one:
> Add new `preventAllClosed` prop to `Accordion`
Originally I was against that, as we had discussed a few times when working on `Accordion` this is just state so people can control it and …
> [Collapsible][Accordion] Rename parts 🔥 + add `collapsible` prop for `type="single"` 🔥 

- .yarn/versions/4120ce26.yml
- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/dialog/src/Dialog.tsx
- packages/react/dismissable-layer/src/DismissableLayer.stories.tsx
- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/focus-scope/src/FocusScope.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- types/global.d.ts
Fix #646
This is a prequel to the modality changes as I bumped into that issue first hand when trying to make a dialog non-modal trying to focus something outside it by calling `event.preventDefault` in `onInteractOutside`.
> Note
:fire: This change affects the event signature of `onPointerDownOutside` and/or `onInteractOutside` for the given components and therefore will need docs updates:
- `AlertDialog`
- `ContextMenu`
- `Dialog`
- `DropdownMenu`
- `Popover`
> Fix `onPointerDownOutside` event issues 🔥 

- .yarn/versions/dadf863a.yml
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
Fixes #656
This PR introduces a quick fix for #656 before we implement things properly in the future (#657) by simply shifting the menu over a little.
As part of this I've also removed all the props that don't make sense on `ContextMenu`.
Only `sideOffset` remained, which I've renamed to `offset` as `side` now doesn't mean much here.
Let me know how you feel about this.
> Note for docs updates:
- 🔥 Remove `ContextMenu.Content` `side` prop
- 🔥 Remove `ContextMenu.Content` `align` prop
- 🔥 Remove `ContextMenu.Content` `alignOffset` prop
- 🔥 Rename `ContextMenu.Content` `sideOffset` prop to `offset`
> [ContextMenu] Fix issue when no padding on Content 🔥 

- .yarn/versions/eedeb2d4.yml
- packages/react/dialog/package.json
- packages/react/dialog/src/Dialog.tsx
- packages/react/dismissable-layer/package.json
- packages/react/dismissable-layer/src/DismissableLayer.stories.tsx
- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/focus-scope/package.json
- packages/react/focus-scope/src/FocusScope.stories.tsx
- packages/react/focus-scope/src/FocusScope.test.tsx
- packages/react/focus-scope/src/FocusScope.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/slot/src/Slot.tsx
- yarn.lock
> Note: Easier to review without whitespace.
Another preliminary PR for the upcoming modality changes.
@jjenzz and I had discussed this at some point, and it's easier to do it now, rather than in the midst of everything else.
It rejigs `FocusScope` and `DismissableLayer` as self-contained primitives using our usual paradigm.
This has the effect of simplifying how they are composed externally as previously render props made it look almost like leaky abstractions.
> [FocusScope][DismissableLayer] Use `Primitive` and `Slot`

- .github/CONTRIBUTING.md
- .yarn/versions/f3b266eb.yml
@andy-hook had a good idea that we should add something like this to help remind ourselves what our architectural goals are.
These are heuristics that Benoit, Pedro and I all followed while at a previous role together and they have worked well so I'm suggesting these as a starting point.
Feel free to suggest alternatives/extras 🙂
> Add heuristics to contributing docs

- .yarn/versions/b475d886.yml
- packages/react/dialog/src/Dialog.tsx
- packages/react/dismissable-layer/src/DismissableLayer.stories.tsx
- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
Something I had discussed with @jjenzz, I regretted adding `onInteractOutside` as a convenience for the already 2 existing callbacks, as it's mostly unnecessary and gives a weird handler signature (both types of events) so I've decided to remove it.
Additionally, it dawned on me that `onFocusOutside` isn't actually accurate as it's not a focus event happening outside, but rather a focus event leaving a particular subtree so I'm renaming it to `onFocusLeave` which is much more accurate.
> Note for docs updates:
- 🔥 Remove `onInteractOutside` from all concerned components
- 🔥 Rename `onFocusOutside` to `onFocusLeave` on all concerned components
> [DismissableLayer] Remove `onInteractOutside` and rename `onFocusOutside` to `onFocusLeave` 🔥 

- .yarn/versions/f5ce1c6e.yml
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/slider/package.json
- packages/react/slider/src/Slider.stories.tsx
- packages/react/slider/src/Slider.tsx
- yarn.lock
- Adds `usePrevious` to prevent `BubbleInput` from bubbling change on initial render
- Adds an `isFormControl` check to `Slider` and `Checkbox` so that `BubbleInput` only renders if these controls are used in forms
- Added stories to show form change event working (multiple thumb version was strangely satisfying to play with 😄 ).
https://user-images.githubusercontent.com/175330/120327568-cdbbd000-c2e1-11eb-8ef6-998e1cf7746b.mp4
> [Slider] Prevent form change event on initial render

- .yarn/versions/c3fe9718.yml
- packages/react/menu/package.json
- packages/react/menu/src/Menu.stories.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/use-direction/src/useDirection.tsx
- yarn.lock
Closes https://github.com/radix-ui/primitives/issues/383
This PR adds submenu functionality to our base `Menu`
Additional primitives have been added to `Menu` to provide consistent submenu support across several consuming components.
Here is an example of how we can use the pieces to provide submenu support inside our components
```jsx
<Menu.Root>
<Menu.Anchor>Open</Menu.Anchor>
<Menu.Content>
<Menu.Item>Item 1</Menu.Item>
<Menu.Item>Item 2</Menu.Item>
<Menu.Sub>
<Menu.SubTrigger>
Open Sub Menu
</Menu.SubTrigger>
<Menu.Content>
<Menu.Item>Sub Item 1</Menu.Item>
<Menu.Item>Sub Item 2</Menu.Item>
</Menu.Content>
</Menu.Sub>
</Menu.Content>
</Menu.Root>
```
> [Menu] Add submenu primitives

- .yarn/versions/7ee8ffe2.yml
- packages/react/switch/package.json
- packages/react/switch/src/Switch.stories.tsx
- packages/react/switch/src/Switch.tsx
- yarn.lock
- Improves accessibility with native label
- Fixes `event.stopPropagation`
- Prevents duplicate click events from firing
- Changes `onCheckedChange` shape to `onCheckedChange?(checked: boolean): void` 🔥 
https://user-images.githubusercontent.com/175330/120490762-9536f780-c3b0-11eb-8594-d61c9d76618b.mp4
> [Switch] Add `BubbleInput` 🔥 

- packages/react/context-menu/package.json
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.stories.tsx
- yarn.lock
Builds on https://github.com/radix-ui/primitives/pull/627
[See discussion](https://github.com/radix-ui/primitives/issues/383)
This PR uses the new submenu primitives from `Menu` to provide submenu support in `ContextMenu` and `DropdownMenu`
Menus can be nested to create sub menus.
```jsx
<ContextMenu>
<ContextMenuTrigger/>
<ContextMenuContent>
<ContextMenuItem>Item 1</ContextMenuItem>
<ContextMenuItem>Item 2</ContextMenuItem>
<ContextMenu>
<ContextMenuTrigger>
Open Sub Menu
</ContextMenuTrigger>
<ContextMenuContent>
<ContextMenuItem>Sub Item 1</ContextMenuItem>
<ContextMenuItem>Sub Item 2</ContextMenuItem>
</ContextMenuContent>
</ContextMenu>
</ContextMenuContent>
</ContextMenu>
```
https://user-images.githubusercontent.com/11708259/116690178-ed916880-a9b0-11eb-969d-644e4237beb9.mov
> [ContextMenu][DropdownMenu] Integrate new submenu parts

- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
We realised that our initial approach of merging the sub trigger part with the trigger part for these would cause `ref` and TS issues. See original discussion here https://github.com/radix-ui/primitives/pull/629#discussion_r643042075
This exposes a new `TriggerItem` part for each component that should be used when rendering an item as a sub menu trigger.
> [ContextMenu][DropdownMenu] Add `TriggerItem` part

- .yarn/versions/91eebb70.yml
- packages/react/radio-group/package.json
- packages/react/radio-group/src/Radio.tsx
- packages/react/radio-group/src/RadioGroup.stories.tsx
- packages/react/radio-group/src/RadioGroup.tsx
- yarn.lock
- Fixes `event.stopPropagation`
- Prevents duplicate click events from firing
- Changes `onValueChange` shape to `onValueChange?(value: string): void` - Finally matches docs 🔥
- Converts `Radio` to a controlled component only because we only use it in `RadioGroup` which controls it. This allowed me to remove `onCheckedChange` from `Radio` because `onCheckedChange` never actually fires with `false` so the name confused me. We just `setValue(props.value)` when a radio is clicked.
https://user-images.githubusercontent.com/175330/120681102-efa88480-c492-11eb-9eae-c2f94555f34d.mp4
> [RadioGroup] Add `BubbleInput` 🔥 

- .yarn/versions/91eebb70.yml
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/radio-group/src/Radio.tsx
- packages/react/switch/src/Switch.tsx
Makes sure we always emit the `BubbleInput` event even if propagation has been stopped. Without this the underlying checkbox/radio wouldn't become checked. We want it to check, we just don't want the event to propagate.
Also adds `defaultChecked` attributes to ensure the default state is submitted with forms.
> [Checkbox][Switch][RadioGroup] Always emit `BubbleInput` event

- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/menu/src/Menu.tsx
This PR adds 2 things:
- adds 100ms delay to before opening a submenu so skimming over them isn't jarring (100ms is what native seems to do here, we've measured in a video recording)
- adds pointer grace for sub-menu navigation. This is a combination of 2 things:
- a grace duration of 300ms where we check for a specific area (see below)
- an area duration where we check the mouse pointer is in a specific triangle area
https://user-images.githubusercontent.com/1539897/120825726-95222d80-c551-11eb-84cc-588df78c561d.mov
> [ContextMenu][DropdownMenu] Add pointer grace for navigation to sub-menus

- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.tsx
**This is the first PR of a few that I will be raising with various accessibility improvements.**
- Adds `aria-labelledby` to `MenuSubContent` and the root `DropdownMenuContent`. Annoyingly the label isn't being read aloud in NVDA but I will look into this separately.
- Creates a new `DropdownMenuRoot` part because there are a bunch of attributes on the root content that are not required in the sub dropdown menus. This was also needed because the root `aria-labelledby` would override the submenu `aria-labelledby` in `MenuSubContent` if this attribute was added to both types within the `DropdownMenu` composition which resulted in incorrect ids for submenus (they would be pointing at the `DropdownMenuTrigger` id).
- Updates `aria-expanded` for sub menu triggers to follow WAI-ARIA spec
> [DropdownMenu] Add `aria-labelledby` to follow spec

- packages/react/context-menu/package.json
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- yarn.lock
- I realised when doing [the `DropdownMenu` bits](https://github.com/radix-ui/primitives/pull/692) that we didn't need two separate contexts for identifying `isInsideContent` and `isSubmenu` so updated this to follow the reduced approach in `DropdownMenu`
- I also thought there isn't much use us having `useControllableState` in sub context menus because the parent menu can't be controlled. They wouldn't be able to force open submenus without first forcing open parent menu which isn't possible. The only benefit the previous approach had was that they could automatically have submenus open after someone opened the parent menu via  `onContextMenu` event but I can't think when this use-case would be relevant. Thoughts?
> [ContextMenu] Bring inline with `DropdownMenu` changes

- packages/react/dropdown-menu/src/DropdownMenu.tsx
Change sparked by this initial discussion https://github.com/radix-ui/primitives/pull/694#discussion_r649067345
Until we add logic to focus the last item on open then opening with `ArrowUp` is not accessible. It also isn't required WAI-ARIA keyboard support so we're removing for now until we can handle this more appropriately.
- Need to update [`ArrowUp` docs](https://radix-ui.com/primitives/docs/components/dropdown-menu#keyboard-interactions).
> [DropdownMenu] Remove `ArrowUp` to open 🔥 

- packages/react/menu/src/Menu.tsx
See https://github.com/radix-ui/primitives/pull/682#issuecomment-860507424
https://user-images.githubusercontent.com/11708259/121894194-c13e6b00-cd16-11eb-8fe7-7dc79b5b1b51.mp4
This is caused by the `onPointerDownOutside` handler closing the submenu before `onFocusOutside` can run, placing the menu in a state where it can no longer perform focus outside thus leaving it stuck in the open state.
Originally started trying to work around but realised that `DropdownMenu` and `ContextMenu` need to handle their own closing behaviour in `onPointerDownOutside` anyway, and so having this in `Menu` is probably at the wrong level.
> [Menu] Fix stuck open state on click

- .yarn/versions/23cbe1a8.yml
- release-process.md
Noticed while reviewing the process. I guess it changed when the docs structure was updated.
> Fix broken link in release doc

- .yarn/versions/68034758.yml
- packages/react/menu/src/Menu.tsx
Fixes https://github.com/radix-ui/primitives/issues/714
The issue was caused by a wrongly reported direction in Safari because it [inconsistently always returns `0`](https://codesandbox.io/s/silent-currying-wn7ny) on `event.movementX` only when it's a pointer event.
> [DropdownMenu][ContextMenu] Submenu Safari compat

- .yarn/versions/fe7ac0a4.yml
- packages/react/toggle-group/src/ToggleGroup.test.tsx
- packages/react/toggle-group/src/ToggleGroup.tsx
Fixes #721
This was the exact same issue we had with `Accordion` in #593 and treated in #594.
> [ToggleGroup] Fix issue when unpressing an item in single controlled group

- .yarn/versions/13d51b8c.yml
- packages/react/slider/package.json
- packages/react/slider/src/Slider.tsx
- yarn.lock
Fixes #730
- Thumb focusing logic fires every time value changes (this fixes `Home` and `End` keypress too)
- Updated to use PointerEvents instead which meant I could remove some `setTimeout` logic
- Renamed `SliderPart` to `SliderImpl` for consistency
There is the following outstanding issue which I will fix in a separate PR:
https://user-images.githubusercontent.com/175330/122761147-d164c600-d293-11eb-8ad9-0c3ac7621a9c.mp4
When the thumb reaches the same value as another thumb, I have to press the arrow one extra time than I should need to for it to move.
> [Slider] Move focus to correct thumb when using keyboard

- .yarn/versions/bd6efb01.yml
- packages/react/slider/src/Slider.tsx
> [Slider] Fix sticky value with keyboard

- .yarn/versions/762fc211.yml
- packages/react/scroll-area/src/ScrollArea.tsx
Fixes #728 
The bug was caused because of the `ScrollAreaScrollbarVisible` part of the union which doesn't have a `forceMount` prop. It looks like this was confusing the type implementation for Stitches and styled-components.
It works fine without these libraries e.g. `React.ComponentProps<typeof ScrollArea.Scrollbar>` reports fine but I've made this change anyway to please external libs. Not sure why they break.
> [ScrollArea] Fix `forceMount` type on `Scrollbar`

- .yarn/versions/f6a8ffd8.yml
- packages/react/alert-dialog/package.json
- packages/react/alert-dialog/src/AlertDialog.tsx
- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/dialog/src/Dialog.tsx
- yarn.lock
Closes #729
This PR:
- brings `Title` and `Description` from `AlertDialog` into `Dialog` itself
- improves upon existing dev warnings with new requirements
- description is optional for `Dialog` but required for `AlertDialog` so that's reflected in the warnings
- "localizes" the messages based on which primitive it is
- links to docs
> [Dialog] Add optional `Title` and `Description` parts

- .yarn/versions/d3fb587e.yml
- packages/react/context-menu/src/ContextMenu.tsx
Closes #701
This PR adds support for long press to trigger opening `ContextMenu` with touch/pen.
> [ContextMenu] Add long press support for touch/pen

- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/dialog/src/Dialog.test.tsx
- packages/react/dialog/src/Dialog.tsx
This PR builds on top of #698 and adds support for non-modal dialogs.
I have done this by splitting the internals in a few components:
- `DialogContent` which will render:
- `DialogContentModalImpl` or `DialogContentNonModalImpl` which will both render:
- `DialogContentPart`
Before I go much further, I'm still in 2 minds about this whether it's any clearer or not so I'd love to get your thoughts on it.
What pushed me towards this was that otherwise with a single component, I ended up with lots of `context.modal ? ` checks or wiring throughout the component.
> [Dialog] Add support for non-modal dialogs

- .yarn/versions/7023f969.yml
- package.json
- packages/react/dialog/src/Dialog.test.tsx
- packages/react/dismissable-layer/src/DismissableLayer.stories.tsx
- packages/react/polymorphic/src/polymorphic.test.tsx
- packages/react/portal/src/Portal.stories.tsx
- packages/react/presence/src/Presence.stories.tsx
- packages/react/primitive/src/extendPrimitive.test.tsx
- packages/react/slider/src/collection.stories.tsx
This PR adds `@typescript-eslint/no-unused-vars` to our lint rules.
I've been caught out a few times when passing destructured props down across several comps and not having a signal to let me know if i'd forgotten to thread a given prop. It should also help mitigate [small things like this](https://github.com/radix-ui/primitives/pull/724).
One drawback is that we'd trigger a warning when intentionally omitting a given prop via `...rest`, but it appears we currently don't do this very often outside of a couple of tests.
Let me know what you think.
> Add no-unused-var lint rule

- packages/react/alert-dialog/src/AlertDialog.tsx
Force `Modal` mode on `AlertDialog` and prevent dismiss on click outside.
> [AlertDialog] Explicit modality

- packages/react/dialog/src/Dialog.tsx
- packages/react/popover/src/Popover.stories.tsx
- packages/react/popover/src/Popover.tsx
This PR builds on top of #700 and adds support for modality options in popovers.
The approach taken here mirrors that of the [Dialog changes](https://github.com/radix-ui/primitives/pull/699).
> [Popover] Add support for modality

- .yarn/versions/ea4f707a.yml
- packages/react/use-body-pointer-events/src/useBodyPointerEvents.tsx
Fixes #631
Fixes #761 
Fixes #762 
Fixes #763
I managed to fix these all in one go eventually. 
@benoitgrelard  I believe I've also managed to provide a solution that merges both of our suggestions. My main concern was to keep the fix within `useBodyPointerEvents` since the issue is a side-effect of pointer-events enabling too soon, but I've only enabled the delay on `pointerdown` (because like you say, that's **when** it's an issue) and it's a touch or pen pointer.
Happy to continue to discuss alternate solutions as well if we have any because obviously, `setTimeout`s are never ideal. 
---------
UPDATE: Delay has been removed in favour of waiting for `click` event. I gave myself the idea here https://github.com/radix-ui/primitives/pull/767#issuecomment-874220750 😅
> [Dialog][AlertDialog][Popover][DropdownMenu] Prevent pointer-events reenabling prematurely (mobile)

- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.stories.tsx
- packages/react/menu/src/Menu.tsx
This PR adds modality support via the `modal` prop in `DropdownMenu` and `ContextMenu`.
I've made the changes in the underlying `Menu` prim. It differs slightly from `Dialog` / `Popover` because `MenuContentImpl` also provides common functionality for submenus and I didn't want to conflate the `Modal` modes straight away in case the submenu impl needs to change in the near term.
> [DropdownMenu][ContextMenu] Add modality support

- .yarn/versions/0919f87a.yml
- packages/react/use-body-pointer-events/src/useBodyPointerEvents.tsx
Resolves issue where `ContextMenu` right press wasn't functioning correctly after https://github.com/radix-ui/primitives/pull/767
> [ContextMenu] Resolve pointer issue with right mouse press

- .yarn/versions/07243d9a.yml
- packages/react/presence/package.json
- packages/react/presence/src/Presence.tsx
- yarn.lock
This change stems from an issue reported here https://github.com/reactwg/react-18/discussions/70#discussioncomment-981133
I was unable to test that it actually fixes the issue described (since we're React 17) but it doesn't break our stories and seems this is somewhere where we should be using `useLayoutEffect` regardless.
> [Presence] Replace `useEffect` with `useLayoutEffect`

- .yarn/versions/94f36198.yml
- packages/react/collection/src/Collection.stories.tsx
- packages/react/collection/src/Collection.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/roving-focus/src/RovingFocusGroup.tsx
Previously `CollectionSlot` included the provider part, so it typically meant that whatever we decided was the root of the collection (in terms of DOM scoping) was also the subtree in which the items would be available.
This was fine for all current usage, but `Select` needs to be able to access the items, when typing whilst the trigger is focused, and we wouldn't necessarily want to add an extra element surrounding the entire select just in order to provide a root for DOM scoping.
So I've basically split up `CollectionSlot` in 2 separate components (`CollectionProvider` and `CollectionRootSlot`).
It doesn't really change the usage much for current components, and it means I can now bring the `CollectionProvider` much higher up the tree as necessary.
> [Collection] Widen usage of items

- .yarn/versions/8b08b58b.yml
- packages/react/polymorphic/src/polymorphic.ts
It's really hard to know for sure if tweaks to polymorphic types are improving performance but I picked a huge component (`ScrollArea`) and recorded a video of me tweaking its types (with and without these changes) to show how TS is able to more quickly report issues now.
The main change here is to remove the `extends keyof JSX.IntrinsicElements` from the generic which would have been slowing down **all components** regardless of whether the `as` prop was being used.
Instead, I check to see if `as` extends an empty string and if so, I type it as `keyof JSX.IntrinsicElements` to enable intellisense when used.
**INTELLISENSE**
https://user-images.githubusercontent.com/175330/125993174-b89e107b-4caa-4485-af6a-55c18b1e9347.mp4
**BEFORE** (~8s) …
> [Polymorphic] Improve performance

- .yarn/versions/8fd68a1a.yml
- packages/react/slider/src/Slider.tsx
These changes stemmed from some original feedback [here](https://github.com/radix-ui/primitives/pull/794#discussion_r676404750).
I removed the `isInitialRenderRef` check because it seems a clearer approach was to check that we have a `value` like before.
> [Slider] Improve SSR fallback logic

- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dialog/src/Dialog.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/popover/src/Popover.tsx
Previously non-modal auto focus was not covering use of the close button. This change applies auto focus for all interactions except when pointer down outside.
> [Dialog][Popover][DropdownMenu] Adjust non-modal auto focus behaviour

- .yarn/versions/b45a43f5.yml
- cypress/integration/ContextMenu.spec.ts
- cypress/integration/DropdownMenu.spec.ts
It took me a while to figure this one out but the flake we were seeing in our Cypress tests is caused by the variability in measurement speed inside popper when it first renders.
See [here where we apply unmeasured styles](https://github.com/radix-ui/primitives/blob/207014676bce54a97bf61d0e703439765ea62a45/packages/core/popper/src/popper.ts#L355-L363) to position popper elements off screen, the tests don't have a problem with this in 90% of cases as it happens so fast not to cause a problem. The issue starts when these measurements don't happen fast enough and cypress starts it's interaction on the offscreen elements (as they technically exist in dom) this will make the menu visibility logic execute with inaccurate coords and remove the content, failing the test.
Important to note that …
> [ContextMenu][DropdownMenu] Fix test flake

- .yarn/versions/b7cee163.yml
- cypress.json
- package.json
- yarn.lock
Upgrade to latest and save ~2s per run by only rendering videos on failure.
> Upgrade to Cypress 8.0.0

- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dialog/src/Dialog.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/popover/src/Popover.tsx
Stemming from https://github.com/radix-ui/primitives/pull/700#discussion_r679043976
Raising for context.
> [ContextMenu][Dialog][DropdownMenu][ContextMenu] Adjust ref naming

- .yarn/versions/ffb28263.yml
- packages/react/alert-dialog/src/AlertDialog.tsx
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/dialog/src/Dialog.tsx
- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/focus-scope/src/FocusScope.stories.tsx
- packages/react/focus-scope/src/FocusScope.test.tsx
- packages/react/focus-scope/src/FocusScope.tsx
- packages/react/menu/src/Menu.stories.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.stories.tsx
- packages/react/popover/src/Popover.tsx
Closes #585
Closes #566
This PR adds modality support to menus, dialogs and popovers. Originally we exposed a very granular api for managing pointer events, scroll locks and focus control. The most common use case for these props was to apply differing levels of modality depending on consumer needs.
By consolidating and streamlining these into a single `modal` prop we are able to reduce the api surface while making the outcome easier and faster to achieve. This change also allows us to provide consistent handling across components and improve some additional handling under the hood.
https://user-images.githubusercontent.com/11708259/125466947-c6f22aaa-c5be-4546-ae5e-b8acacfd477e.mp4
> [Dialog][AlertDialog][Popover][DropdownMenu][ContextMenu] Modality

- .yarn/versions/658485e8.yml
- packages/react/use-body-pointer-events/src/useBodyPointerEvents.tsx
Pointer events were not resetting correctly when pop ups were opening from within other pop ups. This was initially reported here regarding `Dropdown`/`Dialog` composition: https://discord.com/channels/752614004387610674/803656530259738674/874553651417477162
This change ensures we decrease the count at the same time as the reset (when the unmount events have executed).
> [AlertDialog][ContextMenu][Dialog][Popover][DropdownMenu] Fix pointer-events reset

- .yarn/versions/48277b4f.yml
- packages/react/menu/src/Menu.tsx
Hopefully the code comments explain clearly what is going on here 🤞 
Fixes #742.
--------------
UPDATE: The original change I made here was no longer needed as the changes I made to [fix `Dialog.Trigger` / `DropdownMenu.Item` composition](https://github.com/radix-ui/primitives/pull/818) also fixed this.
I've updated the code comments to explain that it covers this case too and the explanation as to why it fixes this is as follows:
>  Browsers wait for our handler logic to execute before executing their own implementation in case we have prevented their default behaviour. Therefore, the menu will unmount before the browser's `pointerup` logic has executed causing `pointerdown` to be stuck in some browsers. In FF this resulted in text selection occurring on the page when moving the mouse …
> [DropdownMenu][ContextMenu] Prevent text selection on menu close in Firefox

- .yarn/versions/7c9a0131.yml
- packages/react/menu/src/Menu.tsx
After https://github.com/radix-ui/primitives/pull/818 was merged, we noticed that submenus weren't closing if you click another submenu trigger. The PR wasn't the cause of the issue, but uncovered some very strange iOS Safari behaviour because we introduced an `onClick` handler. 
In iOS Safari, if a `pointerup` event mounts DOM with an `onclick` handler (incl. noop), the target of the `pointerup` will not receive focus. You can test the following to see the issue (it is not React specific): https://codepen.io/jjenzz/pen/rNmRjWN
The lack of `focus` meant our `onFocusOutside` logic would not fire from submenus when opening a different submenu, leaving them both open.
> [DropdownMenu][ContextMenu] Fix sub trigger focus in iOS Safari

- .yarn/versions/2ab89854.yml
- packages/react/accordion/src/Accordion.stories.tsx
- packages/react/accordion/src/Accordion.tsx
- packages/react/toggle-group/src/ToggleGroup.tsx
- packages/react/toolbar/src/Toolbar.tsx
Realised we could avoid this when I was reviewing [Benoit's recent PR](https://github.com/radix-ui/primitives/pull/842#issuecomment-913781362).
It also bugged me that we had the `With` naming so I rejigged some of the naming conventions for the implementation components.
> [Toolbar] Replace inconsistent type alias prop type

- .yarn/versions/b46af52c.yml
- packages/react/presence/src/Presence.stories.tsx
- packages/react/presence/src/Presence.tsx
Fixes https://github.com/radix-ui/primitives/issues/849
The problem was caused by some state being stuck in `isAnimating` and suspending the unmount. It seems that the animation name getting retrieved from style in [the mount effect](https://github.com/radix-ui/primitives/blob/887228c4eab10aace9132b907e8693a027ae7027/packages/react/presence/src/Presence.tsx#L53) can sometimes return as `none` under certain conditions, that's why this doesn't show in the story. I was wondering if [this comment](https://github.com/radix-ui/primitives/pull/828#discussion_r691191786) was referring to this issue in the past?
Getting the name in the start event makes this behave consistently.
> [Presence] Get `animationName` consistently

- .yarn/versions/0a79b7b8.yml
- packages/react/collapsible/src/Collapsible.stories.tsx
- packages/react/collapsible/src/Collapsible.tsx
- packages/react/hover-card/src/HoverCard.tsx
- packages/react/slot/src/Slot.stories.tsx
- packages/react/slot/src/Slot.tsx
Originally reported here https://discord.com/channels/752614004387610674/803656530259738674/886570819134816317
Sandbox showing issue: https://codesandbox.io/s/kind-violet-v0b1b?file=/src/App.tsx
Sometimes the `Slot` children might be a `false` boolean if someone does `isSomething && <Whatever />` and that would cause `React.Children.only` to throw its error because it expects a React Element.
In the case of `CollapsibleContent` it was doing `isOpen && children`.
> [Collapsible][Slot] Fix `React.Children.only` error

- .yarn/versions/a2d4b456.yml
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/radio-group/src/Radio.tsx
- packages/react/switch/src/Switch.tsx
It looks like when I removed the `display: none` stuff from these, I forgot to hide them from SRs. Noticed while testing this https://github.com/radix-ui/website/pull/240
Without this change, using the virtual cursor allows you to select the hidden input so it reads like there are two controls for SR users. Oops!
> [Checkbox][RadioGroup][Switch] Hide bubble input from SRs

- .yarn/versions/3c930410.yml
- packages/react/slot/src/Slot.stories.tsx
- packages/react/slot/src/Slot.tsx
Pedro noticed that `<Slot className="foo" />` was [giving TS errors](https://codesandbox.io/s/nostalgic-kapitsa-fspsx?file=/src/App.tsx). 
This fixes that but also removes the `event.defaultPrevented` checks we do in `Slot` when composing events. I noticed this when debugging something from Discord #help yday and thought I'd tackle it at the same time since I don't think the `Slot` should determine whether events can be prevented or not. That should be up to the components that are being composed together. I've added a story to show that events can still be prevented correctly.
> [Slot] Improvements

- .yarn/versions/ca283b8d.yml
- packages/react/toolbar/src/Toolbar.tsx
Fixes #949
There doesn't seem to be such a role in the WAI ARIA docs and their toolbar examples don't include this either. It looks suspiciously like a bad find+replace after copy/pasting the menu/menuitem pattern.
Does anyone know of a reason why this should be kept?
> [Toolbar] Remove `toolbaritem` role

- .yarn/versions/a4d03789.yml
- packages/react/dialog/package.json
- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/dialog/src/Dialog.tsx
- yarn.lock
Fixes #887
I'll explain the thoughts I had and what I did here:
The main issue left with being able to create an outer scrolling dialog was that we have `RemoveScroll` in `DialogContent`, therefore making the overlay non-scrollable too.
- The overlay is only used when it's a modal dialog, which incidentally is when we want to remove scroll (sure enough, we were doing this in `DialogContentModal`)
- So I moved `RemoveScroll` inside `DialogOverlayImpl`.
- The only remaining issue was that we also disable outside pointer events from `DialogContentModal`, so that was still preventing scrolling the overlay, for that I specifically re-enable them on the overlay.
- It also required moving the `allowPinchZoom` prop as it was previously on `DialogContent`. I remember almost raising this in the …
> [Dialog][AlertDialog] Enable outer scrolling dialog pattern

- .yarn/versions/e0af1fb6.yml
- packages/react/menu/src/Menu.tsx
- packages/react/radio-group/src/RadioGroup.tsx
- packages/react/roving-focus/src/RovingFocusGroup.tsx
- packages/react/tabs/src/Tabs.tsx
- packages/react/toggle-group/src/ToggleGroup.stories.tsx
- packages/react/toolbar/src/Toolbar.tsx
Fixes #964
I've removed the `aria-orientation` from `RovingFocusGroup` and applied it in the relevant components instead.
> [ToggleGroup] Fix `orientation` a11y

- .yarn/versions/5ad189b9.yml
- packages/react/accordion/src/Accordion.test.tsx
- packages/react/accordion/src/Accordion.tsx
Patch for #958 . Details in issue. Checks `defaultValue` for type to prevent TypeError
> [Accordion] Patch for TypeError on mismatched prop types when `type='multiple'` and `defaultValue='string'`

- .yarn/versions/898c0ebd.yml
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/tabs/src/Tabs.stories.tsx
- packages/react/tabs/src/Tabs.tsx
- packages/react/tooltip/src/Tooltip.tsx
[This discussion](https://github.com/radix-ui/primitives/issues/980) reminded me of something that has been bothering me for some time so thought I'd propose this PR before I head off for the day to discuss whenever.
- Breaking change for tabs. Need to apply `all: unset` or similar to `Tabs.Trigger`.
> [DropdownMenu][Tooltip][Tabs] Use button with `onClick` for trigger

- .yarn/versions/5529b671.yml
- packages/react/accordion/src/Accordion.tsx
- packages/react/collection/src/Collection.tsx
- packages/react/slider/src/Slider.tsx
Adds support for asynchronously rendered items.
> [Accordion] Use `Collection` util

- .yarn/versions/4826891d.yml
- packages/react/slot/src/Slot.tsx
Closes #1013
Admittedly, I don't seem to be able to reproduce the issue but makes sense so I've switched it to use `React.Children.map` to prevent any warnings like that regardless.
> [Slot] Prevent `key` warning

- .yarn/versions/83127137.yml
- packages/react/tooltip/src/Tooltip.tsx
Closes #1010 
Closes #993
I haven't done this for our other components that add `type="button"` since  I don't believe we have had reports regarding those yet. Not sure what thoughts are here though?
> [Tooltip] Remove `type="button"`

- .yarn/versions/c31614bf.yml
- packages/react/dialog/package.json
- packages/react/dialog/src/Dialog.tsx
- packages/react/portal/src/Portal.tsx
- yarn.lock
When I added the new `Dialog.Portal` part, I forgot to portal from inside `Presence` which meant its `context.open` check would rip the dialog parts out before `Presence` could suspend.
~The `Dialog.Portal` just renders a provider instead now so we can read that inside the relevant parts and wrap them in a portal when necessary.~ I map over the `children` and wrap them in `Presence` and `UnstablePortal` instead.
- ✨ &nbsp; New `forceMount` prop on `Dialog.Portal`.
> [Dialog][AlertDialog] Fix `Dialog` unmount animation

- .yarn/versions/a90db96c.yml
- packages/react/dialog/src/Dialog.tsx
I noticed when documenting the release that the prop types for `Dialog.Portal` have the `asChild` prop but it doesn't do anything at the moment. Either we remove it from types or pass it along?
I've gone with passing it along for now in case people want the portal to render a `div`, then they can pass `asChild={false}`. I dunno if that's likely to be a valid use-case though so happy to remove it.
> [Dialog][AlertDialog] Omit `asChild` from `Portal`

- .yarn/versions/f53fead8.yml
- packages/react/id/src/id.tsx
Fixes #1023
It seems some bundlers will try to be clever and convert `import * as React` to `import { useId } from 'react'` which would throw `'useId' does not exist` errors.
This PR adds a workaround to prevent them from trying to do this.
> [All] Fix `React.useId` check bundler issues

- .yarn/versions/817fc7b7.yml
- packages/react/collapsible/src/Collapsible.tsx
I realised while testing the release that the fix prevents the mount animation but then also prevents the close animation (for the item that is open on mount) the first time it is closed.
> [Accordion][Collapsible] Fix prevent mount animation

- .yarn/versions/244db929.yml
- packages/react/tooltip/src/Tooltip.stories.tsx
- packages/react/tooltip/src/Tooltip.tsx
Reverts [the original fix](https://github.com/radix-ui/primitives/pull/1018). We've realised that given the following "Hoverable" a11y criteria, the tooltips should remain open when the mouse moves over them. In which case, applying `pointer-events: none` would fail a11y.
https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus
> [Tooltip] Revert "Fix trigger when another tooltip overlays it"

- .yarn/versions/d0956f67.yml
- packages/react/tooltip/src/Tooltip.tsx
A couple of fixes here so I've left comments inline to clarify what's what.
> [Tooltip] Fix tooltip visibility logic

- packages/react/collection/src/Collection.stories.tsx
Whilst checking every story when working on #1048 I noticed all of the `Collection` stories were broken.
Probably have been broken since we use the scoping of contexts, the scope wasn't matching in `useCollection` usage.
> [Storybook] Fix Collection stories

- .yarn/versions/ee709007.yml
- packages/react/use-previous/src/usePrevious.tsx
Based on our discussion on the expected behaviour of `usePrevious`. The [typical approach](https://usehooks.com/usePrevious/) actually returns the value from the previous **render**, our thinking however is that this is unintuitive and unexpected. Our expectation is that the value should represent the previous `value` that was **different** e.g. the previous value after it was changed, independent of any re-rendering that may occur.
You can see the difference below, notice how the previous value in the "common" demo only meets our expectation for a single render while "Adjusted" consistently meets it no matter how many renders occur.
https://codesandbox.io/s/summer-dream-7qymy?file=/src/App.js
> [usePrevious] Persist return value between renders

- .yarn/versions/e5aea313.yml
- packages/react/dismissable-layer/src/DismissableLayer.tsx
This is tricky one to describe but I'll give it a go 😅 
The original issue was reported [here](https://discord.com/channels/752614004387610674/803656530259738674/930096627895635989) as a `DropdownMenu` bug.
We recently added `pointer-events: 'auto'` to the `Dialog.Overlay` to allow scrollable overlays which broke some `pointer-events` assumptions in `DismissableLayer` (`Dialog.Content`) with the following composition:
```jsx
<Dialog.Root>
<Dialog.Trigger>Open</Dialog.Trigger>
<Dialog.Overlay>
{/* inside overlay */}
<Dialog.Content /> 
</Dialog.Overlay>
</Dialog.Root>
``` 
A `DismissableLayer` would remove its `pointer-events: 'auto'` styles when it detected a child dismissable (e.g. dropdown) so that the child's siblings would inherit `pointer-events: 'none'` from the body. This was a bad …
> [Dialog][AlertDialog] Fix pointer-events management

- .github/workflows/chromatic.yml
- .yarn/versions/7dc42e13.yml
https://www.chromatic.com/docs/github-actions#run-chromatic-on-external-forks-of-open-source-projects
> **Run Chromatic on external forks of open source projects**
>
> You can enable PR checks for external forks by sharing your project-token where you configured the Chromatic command (often in package.json or in the workflow step).
>
> There are tradeoffs. Sharing project-token’s allows contributors and others to run Chromatic. They’ll be able to use your snapshots. They will not be able to get access to your account, settings, or accept baselines. It can be an acceptable tradeoff for open source projects which value community contributions.
> Run Chromatic for external forks

- .yarn/versions/4e4a8b76.yml
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/radio-group/src/RadioGroup.tsx
Fixes #1103
According the the WAI ARIA spec:
- [Checkboxes](https://www.w3.org/TR/wai-aria-practices-1.2/#keyboard-interaction-5) don't activate on enter keypress
- [Radio groups](https://www.w3.org/TR/wai-aria-practices-1.2/#for-radio-groups-not-contained-in-a-toolbar) don't activate on enter keypress when not in a toolbar
- We have a separate `ToolbarToggleGroup` component for toolbars which activates on enter keypress
I also checked WAI ARIA info on `Switch` and switch is fine to activate on enter keypress.
> [Checkbox][RadioGroup] Prevent enter key activation

- .yarn/versions/f78dbf9e.yml
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/tabs/package.json
- packages/react/tabs/src/Tabs.tsx
- packages/react/tooltip/src/Tooltip.tsx
- yarn.lock
Fixes #1059
Also: 
- While fixing, I noticed that non-modal dropdowns don't focus the trigger when closing via trigger click so fixed that too
- Updated the other components where the `onClick` logic was added to ensure this only fires when it's not a mouse click (since these components already have `onMouseDown` or `onPointerDown` handlers for that).
> [DropdownMenu] Fix non-modal dropdown pointer-events

- .yarn/versions/fd1c3d71.yml
- packages/react/presence/src/Presence.tsx
I ran across this issue when using the render prop to pass `present` to a node outside of the `<Presence/>` tree. If the node has a long running animation and is removed early i.e. its parent unmounts, then `present` remains `true`. My expectation is that it would flip to `false` when the node is removed.
The `animationcancel` event does fire on node removal, but as we cleanup those handlers inside the effect they don't appear to run when the node is cleared.
https://codesandbox.io/s/youthful-feather-ifsvk?file=/src/App.js
> [Presence] Account for early node removal

- .yarn/versions/573f03d4.yml
- packages/react/use-size/src/useSize.tsx
Raising for discussion. Setting `undefined` in the cleanup means we can't smoothly transition between values when switching nodes.
Contrived example:
https://codesandbox.io/s/charming-glitter-2fx1q?file=/src/App.js
> [useSize] Avoid `undefined` when switching nodes

- .yarn/versions/704c1b17.yml
- packages/react/tabs/src/Tabs.tsx
Fixes #1113
The proposed change to solve the linked issue here is to prevent focus from happening if it's not a left click.
> [Tabs] Prevent accidental focus activation via right-click

- .yarn/versions/9b75b880.yml
- packages/react/collapsible/src/Collapsible.stories.tsx
- packages/react/collapsible/src/Collapsible.tsx
Fixes https://github.com/radix-ui/primitives/issues/1074 by allowing to add an animation-fill-mode. 
When using the [Collapsible](https://github.com/radix-ui/primitives/tree/main/packages/react/collapsible) with React 18 Concurrent Mode, the close animation flickers. This is due to the fact, that it takes too long (not quite sure why) for the content to be hidden/unmounted. Since the [animation](https://www.radix-ui.com/docs/primitives/components/collapsible#animating-content-size) doesn't specify any fill-mode, the animation styles will only be applied during the execution of the animation. Therefore the content height is animated to 0 during the animation but jumps back to its original size afterwards, before beeing unmounted.  Adding `animation-fill-mode: forwards` fixes that issue …
> [Collapsible][Accordion] Fix content animation of collapsible

- .yarn/versions/e62b671c.yml
- packages/react/label/src/Label.tsx
This is coming off the back of when I worked on labelling with `Select` and realised that depending on wrapping vs. `htmlFor` strategy, the labelling order would potentially differ.
Incidentally, it also probably make more sense to announce the label first (if there are 2 like in the case of select).
> [Label] Consistent label ordering for screen readers

- .yarn/versions/48dc3631.yml
- packages/react/alert-dialog/src/AlertDialog.tsx
- packages/react/dialog/src/Dialog.test.tsx
- packages/react/dialog/src/Dialog.tsx
Fixes #1094
Right [now](https://github.com/radix-ui/primitives/blob/28c4fd981319992458757d860c26942fed703419/packages/react/dialog/src/Dialog.tsx#L82) the `dialog` component always generates a `descriptionId` even if no description component is registered.
This leads to [always](https://github.com/radix-ui/primitives/blob/28c4fd981319992458757d860c26942fed703419/packages/react/dialog/src/Dialog.tsx#L399) generate an `aria-describedby` even if no description has been added.
- 🔥 `aria-label` will be ignored, use `Title` with `<VisuallyHidden asChild>`
- ✨  Use `aria-describedby={undefined}` to silence missing description warning
> [Dialog][AlertDialog] Add aria-describedby only when a description is provided

- .yarn/versions/4a09fd00.yml
- packages/react/dismissable-layer/package.json
- packages/react/dismissable-layer/src/DismissableLayer.tsx
- yarn.lock
Our current implementation assumes that layers will always be opened from within another layer so escape keypress would close based on React tree. However, with `Toast`, they're opened as siblings (not from inside each other) and escape should close one at a time. 
These changes update `DismissableLayer` to order layers based on creation order rather than the React tree order.
Here's some manual testing showing existing expectations are still working:
https://user-images.githubusercontent.com/175330/153633217-94e58f05-b4ae-4572-877b-a2b777e42542.mp4
https://user-images.githubusercontent.com/175330/153633388-d5a4b385-d9d8-42f1-9633-f5d3ba344de9.mp4
> [DismissableLayer] Add sibling support

- .yarn/versions/4e063ba5.yml
- packages/react/dismissable-layer/src/DismissableLayer.tsx
Needed for `Toast`. When a `DismissableLayer.Branch` is rendered, it will force any rendered `DismissableLayer.Root`s to consider the branch node inside the `DismissableLayer`.
In other words, pointer outside and focus outside etc. events will not fire when interacting with a branch.
> [DismissableLayer] Allow external nodes to be considered inside

- packages/react/toast/src/Toast.tsx
An update for `duration` prop was instantly closing the toast. This was happening because the `closeTimerRemainingTimeRef` was `Infinity` from the previous render closure so `setTimeout(handleClose, Infinity)` was instantly executing.
We do `closeTimerRemainingTimeRef  = React.useRef(duration)` when initially rendered but never updated this when the duration changed.
> [Toast] Fix promise story

- packages/react/toast/src/Toast.tsx
I noticed that pointer down on `Action` and moving mouse away to release (cancel your action) would still click the action because I had set pointer capture regardless of swipe direction.
This ensures pointer is only captured when swiping in the specified `swipeDirection`.
> [Toast] Pointer capture on swipe only

- packages/react/navigation-menu/src/NavigationMenu.tsx
Previously if you were controlling you'd have to provide your own `value` to items as the `autoValue` was changing every render. Now consumers only need to provide a `value` on items if they need specific access, otherwise it'll continue to work using `autoValue`.
> [NavigationMenu] Consistent auto value

- packages/react/toast/src/Toast.stories.tsx
- packages/react/toast/src/Toast.tsx
Escape keypress will close the most recent toast unless a toast is focused, in which case, it will close the focused one.
https://user-images.githubusercontent.com/175330/155144594-fa47582a-71b1-4322-836e-fc9a55131691.mp4
> [Toast] Close focused toast on escape keypress

- packages/react/navigation-menu/src/NavigationMenu.tsx
Previously pointer events intended for mouse hover intent were firing on touch, causing unexpected dismissals. This change ignores those hover intent interactions on touch.
> [NavigationMenu] Ignore mouse intent on touch

- .yarn/versions/a91622a8.yml
- packages/react/select/package.json
- packages/react/toast/package.json
Doh 😅
This meant that the `dist` file was removed when publishing and we ended up with empty published packages. This must have been copy/pasted from an old architecture when we started these comps. Oops!
> Remove package clean scripts

- .yarn/versions/cf522e27.yml
- packages/react/navigation-menu/package.json
- packages/react/navigation-menu/src/NavigationMenu.tsx
- yarn.lock
Safari was having problems applying the correct `Viewport` dimensions if using `scale/rotate` animations on open. This is because it was falling back to `getBoundingClientRect` inside `useSize` as it [doesn't support `borderBoxSize` yet](https://caniuse.com/mdn-api_resizeobserverentry_borderboxsize). `getBoundingClientRect` returns dimensions **after** transform, hence the issue.
Switching to trusty `offsetWidth/height` works as expected. I considered making this change at the `useSize` level but I think it warrants further testing across other consumers first.
Before:
https://user-images.githubusercontent.com/11708259/155436308-96e656a9-cb57-4877-8579-4f1bacdf307e.mp4
After:
https://user-images.githubusercontent.com/11708259/155436327-efd16efa-5b4b-4093-a015-8547d0696984.mp4
> [NavigationMenu] Fix `Viewport` size calculation in Safari

- .yarn/versions/aa52d28a.yml
- packages/react/navigation-menu/src/NavigationMenu.stories.tsx
- packages/react/navigation-menu/src/NavigationMenu.tsx
Switch to `useId` and provide deterministic non empty string ID for initial render to avoid open flash.
> [NavigationMenu] Fix SSR autoValue mismatch

- .yarn/versions/3abef429.yml
- packages/react/toast/src/Toast.tsx
> [Toast] Allow `children` in `Viewport` types for `asChild` composition

- .yarn/versions/f27979d2.yml
- packages/react/select/src/Select.tsx
Fixes #1244
The `asChild` would strip out the context provider because it was inside the `Primitive.div`. This moves it outside.
Easier to review with hidden whitespace changes.
> [Select] Fix SelectContent asChild prop

- .yarn/versions/0c1db6bc.yml
- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/dialog/src/Dialog.tsx
Closes #1061
Current implementation required `forceMount` to be added to all three parts which was unintuitive.
- Shares prop from portal
- Adds `ForceMount` story to Chromatic output to highlight breaking changes with `forceMount` in future
**Note: Not sure why it isn't force mounted in the Chromatic story lol, ack. I'll figure that out in a bit.**
> [Dialog][AlertDialog] Share `forceMount` from Portal

- .yarn/versions/4c8bef63.yml
- packages/react/tooltip/package.json
- packages/react/tooltip/src/Tooltip.stories.tsx
- packages/react/tooltip/src/Tooltip.tsx
- yarn.lock
Fixes #937
**Note:** We had discussed in the issue potentially implementing this at the `Popper` layer as it could be useful for other components that open and are attached to a trigger. However, it's not possible there because the notion of "open/closed" doesn't exist at that level but is implemented in each primitive.
For that reason, I implemented it only in `Tooltip` for now so it's easy to review, and we can create a separate issue to maybe abstract that in its own package and implement within others.
> [Tooltip] Better "close on scroll" implementation

- .yarn/versions/8edec830.yml
- packages/react/accordion/package.json
- packages/react/checkbox/package.json
- packages/react/collapsible/package.json
- packages/react/collapsible/src/Collapsible.stories.tsx
- packages/react/presence/package.json
- packages/react/presence/src/Presence.stories.tsx
- packages/react/presence/src/Presence.tsx
- packages/react/radio-group/package.json
- packages/react/scroll-area/package.json
- yarn.lock
closes https://github.com/radix-ui/primitives/issues/1074
related https://github.com/radix-ui/primitives/pull/1292 https://github.com/radix-ui/primitives/pull/1125
The introduction of batched updates across all handlers in 18 concurrent mode introduces a frame sync issue where the state transition (`unmount`) is communicated a frame after animation has completed.
Currently we are recommending `animation-fill-mode: forwards` to cover this gap. While it does work, it [creates other problems](https://github.com/radix-ui/primitives/discussions/1311).
I'm still getting my head around the internal mechanics of react scheduling so feedback here would be very welcome, but as it stands I feel that this change is a superior option vs the css we are recommending.
⚠️  Note for docs: Remove `forwards` …
> [Presence] React 18 – Fix animation frame sync flicker 

- .yarn/versions/57842fe3.yml
- packages/react/select/src/Select.tsx
Closes #1350
We make sure our heuristic doesn't apply too eagerly when there are less items.
> **Note**: Whilst testing for this, I noticed a bunch of alignment stuff is broken :( probably due to the React 18 upgrade given nobody has reported yet… I'm gonna add a separate issue to track and will take a look.
> [Select] Fix positioning issue when few items are present

- .yarn/versions/bb0efa48.yml
- packages/react/tooltip/src/Tooltip.tsx
Fixes https://github.com/radix-ui/primitives/issues/1354
Also moved mouse events to pointer to align with recent approaches. This is a breaking change for tests triggering these events or consumers preventing behaviour.
> [Tooltip] Standardise on `pointerEvent`, don't open on touch

- .yarn/versions/4b125ae7.yml
- ssr-testing/package.json
- yarn.lock
Noticed the upgrade to 18 created a mismatch in our deps for the SSR playground.
As we import code directly via `externalDir`, aligning the versions resolves it.
> Fix React resolution issue in SSR test app

- .yarn/versions/5e7f60d9.yml
- packages/react/navigation-menu/src/NavigationMenu.tsx
See https://github.com/radix-ui/primitives/issues/1364#issuecomment-1116216373
- Adds an `onSelect` custom event so that we can maintain consistent "out of the box" close behaviour when composing with `next/link` (and others)
- Provides a mechanism to opt out of close on select without affecting default navigation behaviour (as they would if they simply `onClick={e => e.preventDefault()}`)
> [NavigationMenu] Improve router link event composition

- .yarn/versions/10369624.yml
- packages/react/slot/src/Slot.stories.tsx
- packages/react/slot/src/Slot.test.tsx
- packages/react/slot/src/Slot.tsx
- packages/react/slot/src/__snapshots__/Slot.test.tsx.snap
> [Slot] Fix children expectation when using `Slottable`

- .yarn/versions/64cb0ea5.yml
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
Fixes #1324 
I've managed to do even slightly better than we had tested. It will now align not with the first item, but the first non-disabled item. This gives a better experience if some of the first items are disabled.
I've added a chromatic story for it too.
> **Note**: Best to review individual commits
> [Select] When there's no `value` or `defaultValue`, align with first non-disabled item

- .yarn/versions/272fbd8c.yml
- packages/react/menu/src/Menu.stories.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
Closes #1289
> Note: I also renamed `data-state="active|inactive"` to `data-state="checked|unchecked"` in `Select` to avoid confusion and bring inline with menus.
> [Menu][Select] Add `data-highlighted` attribute

- .yarn/versions/c0df45fc.yml
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
- ssr-testing/pages/select.tsx
> [Select] Add placeholder support

- .yarn/versions/f0b57fd8.yml
- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/primitive/src/Primitive.tsx
- packages/react/roving-focus/src/RovingFocusGroup.tsx
- packages/react/toast/src/Toast.tsx
- packages/react/tooltip/src/Tooltip.tsx
Some wider changes in https://github.com/radix-ui/primitives/pull/1378 were a little overzealous as `flushSync` was unexpectedly being called during lifecycle in some cases.
In `Tooltip` this was clear because `onChange` is [called during lifecycle](https://github.com/radix-ui/primitives/blob/c92d43343f1233a94a41d12c5eb56a42b72dc98e/packages/react/use-controllable-state/src/useControllableState.tsx#L49), `RovingFocusGroup` and `Toast` were due to `focus` / `focusout` being called either during mount or during teardown.
Interesting to note the implicitness of the `focusout` case due to the browser removing the nodes and then firing the event.
> [RovingFocusGroup][Toast][Tooltip] Avoid flushing dispatch when called in lifecycle

- .yarn/versions/29c9cc74.yml
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- Provides `Sub` part in place of implicit nesting to create sub menus
- Renames `TriggerItem` to `SubTrigger` to align with the additional part
I looked into this again briefly https://github.com/radix-ui/primitives/issues/1016#issuecomment-989842648 but the static typing limitations (having two different element and prop types for one part) remains the same.
> [DropdownMenu] Expose explicit `Sub` part

- .yarn/versions/5305d6b7.yml
- packages/react/context-menu/package.json
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- yarn.lock
- Provides Sub part in place of implicit nesting to create sub menus
- Renames `TriggerItem` to `SubTrigger` to align with the additional part
- Provides props for `Sub` to be controlled
The controlled prop change is more of a consistency thing, controlling submenus hasn't actually been requested much afaik, but it makes sense to allow it here as it is in other prims.
> [ContextMenu] Expose explicit `Sub` part

- .yarn/versions/33a18aeb.yml
- packages/react/scroll-area/src/ScrollArea.tsx
This PR adds the `Impl` part to separate the hook logic in the `ScrollArea` component. It addresses https://github.com/radix-ui/primitives/pull/1392#issuecomment-1126938126
> [ScrollArea] Add `ScrollAreaThumbImpl` part

- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.tsx
- Tidies up nesting logic
- Exposes `SubContent` part with accurate prop typings
I haven't re-ordered anything in the file yet to make the diff easier to read, not sure if we think it would be best to move them to the bottom of the file as well.
> [DropdownMenu][ContextMenu] Improve `SubContent` types

- .yarn/versions/9dea0877.yml
- packages/react/tabs/package.json
- packages/react/tabs/src/Tabs.stories.tsx
- packages/react/tabs/src/Tabs.tsx
- yarn.lock
closes https://github.com/radix-ui/primitives/issues/860
Very similar to our approach for [`Collapsible`](https://github.com/radix-ui/primitives/blob/415a3e1173c81829adcda88c0f02e57df3dedbab/packages/react/collapsible/src/Collapsible.tsx#L182-L185) with a couple of modifications (we don't need to measure in this case). I assume we have historic / a11y reasons for controlling render of `children` rather than on wrapping element, hence my use of the render prop in this instance.
> [Tabs] Add animation support for content

- .yarn/versions/5a76db20.yml
- packages/react/primitive/src/Primitive.tsx
> **Note**: easier to review without whitespace
I was debugging some stuff in `Select` in react developer tools and noticed a lot of `Anonymous` components in the tree.
It was mostly all of the `Primitive.x` nodes, so I've added a display name to them to reflect it, makes it much more obvious what you're looking at.
I've noticed a few other mismatch related to display names that I might try to look at separately but this was the biggest one.
> [Primitive] Improve debugging

- .yarn/versions/c204ee30.yml
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
This was originally changed in https://github.com/radix-ui/primitives/pull/1394
In hindsight it's less ergonomic and inconsistent when used alongside `data-state` attributes etc.
> [DropdownMenu][ContextMenu] Make css variable name consistent on `Content`

- .yarn/versions/44602c5e.yml
- cypress/integration/Select.spec.ts
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
- ssr-testing/pages/select.tsx
Closes #1223
> **Note**: easier to review without whitespace
> [Select] Fix mismatch with hidden native select

- .yarn/versions/aa7247ea.yml
- packages/react/dismissable-layer/src/DismissableLayer.tsx
Basically just call `preventDefault`! I’m not sure about the semantics of `onDismiss` being undefined, but I _think_ if it’s undefined, we shouldn’t be preventing the default—I’m open to input on that.
Fixes radix-ui/primitives#1420
> [DismissableLayer] Don't exit fullscreen when esc-ing out of a layer

- .yarn/versions/345d09c7.yml
- packages/react/tooltip/src/Tooltip.stories.tsx
- packages/react/tooltip/src/Tooltip.tsx
- ssr-testing/pages/tooltip.tsx
Closes #1304
>**Warning**: This is based on #1306 branch because of the changes in `Popper`.
We will need to be merged in correct order, and run version check too.
> **Note**: Easier to review without whitespace
The implementation is the same as what's in `Popover`.
---
> **Warning**
> Breaking changes in docs:
> - new `Portal` part, with `forceMount` and `container` props, meaning default has changed (not portalled if not using new part)
> - lose `portalled` prop on `Content`
> - different default for `forceMount` on `Content`
> - manual z-index management
> - update demos/marketing comps
> [Tooltip] Expose `Portal` part

- .yarn/versions/1bf02bd7.yml
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.stories.tsx
- packages/react/menu/src/Menu.tsx
- ssr-testing/pages/dialog.tsx
- ssr-testing/pages/dropdown-menu.tsx
- ssr-testing/pages/hover-card.tsx
Closes #1302
Closes #1303
>**Warning**: This is based on #1306 branch because of the changes in `Popper`.
We will need to be merged in correct order, and run version check too.
> **Note**: Easier to review without whitespace
The implementation is mostly the same as what's in `Popover`, although this one has an extra level of extension through `Menu`.
**The work is done, BUT I haven't had much time to test different situations when you use the portal or not. I suspect we need to pay a bit more attention to this one, because it used to not always expose `portalled` before. Sometimes it was hardcoded (like for sub-menus), etc**
---
> **Warning**
> Breaking changes in docs:
> - new `Portal` part, with `forceMount` and `container` props, meaning default has changed (not portalled if not using …
> [DropdownMenu][ContextMenu] Expose new `Portal` part

- .yarn/versions/19f95876.yml
- packages/react/dismissable-layer/src/DismissableLayer.stories.tsx
- packages/react/menu/package.json
- packages/react/menu/src/Menu.tsx
- packages/react/popover/package.json
- packages/react/popover/src/Popover.tsx
- packages/react/select/package.json
- packages/react/select/src/Select.tsx
- yarn.lock
> **Note**: Easier to review without whitespace.
I realised a [change](https://github.com/radix-ui/primitives/pull/936/files#r736472636) we made to `Dialog` a long time ago wasn't carried over to other components.
Essentially this uses the fact that `RemoveScroll` has an `as` prop, combining it with our `Slot` to remove the extra wrapping div added by `RemoveScroll` without losing its functionality, essentially attaching it to our content element (or its wrapper).
> [Menu][Popover][Select] Minimise number of extra divs

- .yarn/versions/dc9df257.yml
- packages/react/context-menu/src/ContextMenu.stories.tsx
- packages/react/context-menu/src/ContextMenu.tsx
Reviewing the new data-attributes PR on the docs, I realised that we never added `data-state` to `ContextMenu.Trigger` even though we specifically were controlling it in all stories to achieve that style 😀 Not sure why we never did, probably just an omission.
> [ContextMenu] Add `data-state` to `Trigger`

- packages/react/dialog/src/Dialog.tsx
- packages/react/dismissable-layer/src/DismissableLayer.stories.tsx
- packages/react/hover-card/src/HoverCard.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/popper/src/Popper.stories.tsx
- packages/react/portal/package.json
- packages/react/portal/src/Portal.stories.tsx
- packages/react/portal/src/Portal.tsx
- packages/react/select/src/Select.tsx
- packages/react/toast/src/Toast.tsx
- packages/react/tooltip/src/Tooltip.tsx
- yarn.lock
> **Note**: needs to be rebased once #1459 is merged
---
> **Warning**
> Breaking changes in docs:
> - Breaking changes for `Portal` util: manual z-index management + `containerRef` to `container` prop
> - update docs page for `Portal`
> [Portal] Kill old portal and replace with new one

- .yarn/versions/5b3099df.yml
- packages/react/select/package.json
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
- ssr-testing/pages/select.tsx
- yarn.lock
> **Note**: Easier to review without whitespace. Might be even easier commit by commit.
- Add missing focus guards https://github.com/radix-ui/primitives/commit/e88481cdbcac53b8de93e7f0fde82353faafd1e3
- Add support for `allowPinchZoom` https://github.com/radix-ui/primitives/commit/96dcffaa847be3b60355da4faab0d344847224e3
- Expose new portal part https://github.com/radix-ui/primitives/commit/43cb78a5b763c1557885cad279b64c21581d53f4
- Copy z-index to wrapper https://github.com/radix-ui/primitives/commit/41ed89b59618ba494010088bc9056fb618ee015d
---
> **Warning**
> Breaking changes in docs:
> - new `Portal` part, with `container` prop
> - manual z-index management
> - update demos/marketing comps
> [Select] Bring parity with other primitives

- .yarn/versions/6629a53c.yml
- cypress/integration/Toast.spec.ts
- packages/react/toast/package.json
- packages/react/toast/src/Toast.stories.tsx
- packages/react/toast/src/Toast.tsx
- yarn.lock
fixes https://github.com/radix-ui/primitives/issues/1322
builds on https://github.com/radix-ui/primitives/pull/1468
> Most recent should be tabbed to first and unfortunately, most recent will be at the bottom of the viewport DOM.
As described in https://github.com/radix-ui/primitives/issues/1322 – We use portals to move `Toasts` into the `Viewport`, out of the box this causes issues with keyboard accessibility as the append only nature of portals means our source order places most recent toasts last. We were previously using mutation observer to re-order the DOM and solve for it, unfortunately this causes issues with animation libraries which depend on a stable DOM order.
After much investigation there appears to be no fool proof way to re-order DOM without causing issues downstream. …
> [Toast] Manually reverse tab order

- .yarn/versions/374cfd97.yml
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/dialog/src/Dialog.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/select/src/Select.tsx
- `allowPinchZoom` was `false` by default, which is by default an accessibility issue.
- It also means if users want it back, it's impossible to bring back without the extra prop
- after experimenting with our own remove scroll ideas during hack week, we concluded pinch zooming should be allowed by default and that if users want to disallow that, they can do it themselves, so we're removing the prop and hardcoding to `true` for now so we don't create an extra breaking change for it after v1.
> [AlertDialog][ContextMenu][Dialog][DropdownMenu][Popover][Select] Remove `allowPinchZoom` prop

- .yarn/versions/8c65455f.yml
- packages/react/tooltip/src/Tooltip.stories.tsx
- packages/react/tooltip/src/Tooltip.tsx
fixes https://github.com/radix-ui/primitives/issues/620
Of the options available we decided on:
> Create an invisible track from the triggering element to the tooltip content that won't trigger mouseOut event.
https://user-images.githubusercontent.com/11708259/175526607-c926c537-dd37-43b7-a029-90944356a8de.mp4
> [Tooltip] Content accessible via pointer

- .yarn/versions/65e485ad.yml
- packages/react/popper/src/Popper.tsx
Forgot to remove it from the types before…
> [Popper] Remove old `offset` prop from `Arrow`'s types

- .yarn/versions/8da3c08f.yml
- packages/react/toolbar/src/Toolbar.test.tsx
- packages/react/toolbar/src/Toolbar.tsx
Fixes issue with Toggle Item firing Click event twice, bug reported here:
https://github.com/radix-ui/primitives/issues/1525
This PR was based into another related issue reported back in january
https://github.com/radix-ui/primitives/pull/1157
The PR follows same principle, creating an scoped preventing multiple click event to be triggered, also i've added a Unit test to ensure the Click gets called just once.
> Prevent ToolbarItem click from firing twice

- .yarn/versions/4cffd0d5.yml
- packages/react/toast/src/Toast.stories.tsx
- packages/react/toast/src/Toast.tsx
builds on https://github.com/radix-ui/primitives/pull/1668
closes https://github.com/radix-ui/primitives/issues/1453
supercedes https://github.com/radix-ui/primitives/pull/1477
> [Toast] Add `onPause` and `onResume`

- .yarn/versions/975c6613.yml
- packages/react/dropdown-menu/src/DropdownMenu.tsx
This fix should prevent passing `onKeyDown` to the focused `DropdownMenuItem` from `DropdownMenuTrigger` which triggered `onClick` event on `a` or `button` elements.
---
Closes #1268
Closes #1397
Closes #1622
Closes #1655
> [DropdownMenu] Prevent passing keydown event to the focused MenuItem from MenuTrigger

- .yarn/versions/7845b662.yml
- packages/react/toast/src/Toast.tsx
Address timer issues mentioned in https://github.com/radix-ui/primitives/pull/1669#issuecomment-1252282997
The underlying issue is that the pause handling doesn't account for multiple calls in succession. Because we're now exposing `onPause` and `onResume` it made more sense to address the issue at source with the duplicate events being fired.
@benoitgrelard might be easier to hop on a call to go over this.
> [Toast] Fix timer issues

- .yarn/versions/cd691ba7.yml
- packages/react/tooltip/src/Tooltip.tsx
closes #1691 
**What was done?**
Cancel the **trigger** event **onClick**. 
**More details?**
The tooltip appears if the user stays hovered over the trigger component, but if the user clicks the trigger before the timeout activates the tooltip(which by default is 700ms), then the tooltip text no longer appears.
https://user-images.githubusercontent.com/25510810/192797127-7262d02a-9a80-4739-8215-54b3136a93f9.mov
> [Tooltip] Shouldn't open if trigger is clicked **before** the tooltip opens

- .yarn/versions/8165e81a.yml
- packages/react/dismissable-layer/src/DismissableLayer.stories.tsx
- packages/react/dismissable-layer/src/DismissableLayer.tsx
- packages/react/dropdown-menu/src/DropdownMenu.stories.tsx
- packages/react/use-escape-keydown/src/useEscapeKeydown.tsx
Adding event handlers  to the `document` global is not correct when the element is rendered in a popup window. This changes the `usePointerDownOutside`, `useFocusOutside` and `useEscapeKeydown` hooks used by `DimissableLayer ` to take into account the correct document.
Fixes #1676
> [DismissableLayer] Add DOM event handlers to ownerDocument

- .yarn/versions/7473ecfc.yml
- packages/react/hover-card/src/HoverCard.stories.tsx
- packages/react/hover-card/src/HoverCard.tsx
closes https://github.com/radix-ui/primitives/issues/1470
supersedes https://github.com/radix-ui/primitives/pull/1479
Scope user selections to the content, improve dismiss handling to improve highlighting UX.
Builds on the work by @innub in https://github.com/radix-ui/primitives/pull/1479 but with added Safari support and some improvements to avoid dismissing while attempting to highlight in certain situations:
https://user-images.githubusercontent.com/11708259/192782489-9ae3effb-9f32-43bf-b93c-4b4a7f22118e.mp4
> [HoverCard] Contain user text selections

- .yarn/versions/f15929a4.yml
- packages/react/radio-group/src/RadioGroup.stories.tsx
- packages/react/radio-group/src/RadioGroup.tsx
- packages/react/roving-focus/src/RovingFocusGroup.stories.tsx
- packages/react/roving-focus/src/RovingFocusGroup.tsx
Allows setting `disabled` on the root `RadioGroup`, setting all `Radio` items as `disabled`.
The `RovingFocusGroup` has be altered to become unfocusable when it has no focusable items.
> [RadioGroup] Add `disabled` prop to `Root`

- .yarn/versions/d05a249e.yml
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
This will add `disabled` prop to `<Select.Root>` to disable its trigger and the BubbleSelect when it's inside a form.
It's different from disabling the trigger only because the select value will not be submitted
> [Select] Add `disabled` prop to `Root`

- .yarn/versions/6eeb83fc.yml
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
> [Select] Add required prop

- .yarn/versions/4f235e95.yml
- packages/react/collapsible/src/Collapsible.tsx
closes https://github.com/radix-ui/primitives/issues/1265
After some exploration it dawned that perhaps these browsers need a little bump to replay the animation from scratch for the initial size retrieval.
I'll try and validate this behaviour in a smaller example but this does fix the issue.
@benoitgrelard Do you remember why we moved away from the [clearing the shorthand](https://github.com/radix-ui/primitives/pull/1044/files) in the first place? I remember that had problems but i'm questioning if removing the name property alone is all we need.
> [Collapsible][Accordion] Fix initial animation playback in Firefox and Safari

- .yarn/versions/abb4a072.yml
- packages/react/slot/src/Slot.stories.tsx
- packages/react/slot/src/Slot.tsx
> [Slot] Don't eagerly create callbacks

- .yarn/versions/790cf30d.yml
- packages/react/menu/src/Menu.tsx
Fixes an issue where typeahead wouldn't work on menus if the user changes the "role" attribute of the menu content component (e.g. by setting `role="listbox"`).
Hit this when implementing a custom "select multiple" component on top of a dropdown menu. When changing the role of the menu to "listbox", typeahead would no longer work.
> [Menu] Support typeahead without "menu" role

- .yarn/versions/82e6e50f.yml
- packages/react/select/src/Select.tsx
Fixes https://github.com/cypress-io/cypress/issues/24459
> Looks like the invalid pointer ID is thrown If the pointerId does not match any the active pointers and so returns void and throws a DOMException with the name InvalidPointerId . I believe this is happening because the captured pointer is being automatically released by firefox a fraction earlier, so by the time the pointerdown listener is called, the component no longer has a valid pointerID as it has implicitly been released thereby throwing an error.
>
> According to https://www.w3.org/TR/pointerevents3/#implicit-pointer-capture "the [hasPointerCapture](https://www.w3.org/TR/pointerevents3/#dom-element-haspointercapture) API may be used (eg. within any [pointerdown](https://www.w3.org/TR/pointerevents3/#dfn-pointerdown) …
> [Select] fix invalid pointerId in Firefox Cypress test

- .yarn/versions/abf963b1.yml
- packages/react/hover-card/src/HoverCard.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/popper/package.json
- packages/react/popper/src/Popper.tsx
- packages/react/select/package.json
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
- packages/react/select/src/index.ts
- packages/react/tooltip/src/Tooltip.tsx
- yarn.lock
> [Select] Add ability to position as popper

- .github/workflows/build.yml
- .github/workflows/publish-rc.yml
- .github/workflows/version.yml
- .yarn/versions/1b9a477c.yml
Remove use of set-output from GitHub actions, which has been deprecated
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Remove use of deprecated set-output

- .yarn/versions/132571b4.yml
- packages/react/context-menu/src/ContextMenu.tsx
- packages/react/dropdown-menu/src/DropdownMenu.tsx
- packages/react/hover-card/src/HoverCard.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/tooltip/src/Tooltip.tsx
Fixes #1596
Closes #393
This PR re-namespaces the newly available custom properties from `Popper` into dependent components (`ContextMenu`, `DropdownMenu`, `HoverCard`, `Popover`, `Tooltip`).
These were introduced in `Popper` and used in `Select` here: #1853
---
Related PRs (now redudant): #1597, #1659
> Re-namespace new custom properties from `Popper`

- .yarn/versions/c21771b2.yml
- packages/react/menu/src/Menu.tsx
Fixes radix-ui/primitives#1751
I kept looking at it, and I think this is probably the right place for this `preventDefault`? It even seems like another option for `composeEventHandlers` that would automatically `preventDefault` might make sense. I don't wanna tell you how to design your library, though.
> [DropdownMenu][ContextMenu] Don't exit fullscreen when esc-ing out of a submenu

- .yarn/versions/a93e3f6a.yml
- packages/react/menu/src/Menu.tsx
This makes using `CheckboxItem` with TypeScript a bit simpler, as it doesn't require state managed up the tree to allow indeterminate states if it doesn't want to. More practically, it makes this allowed:
```tsx
const [checked, setChecked] = useState(false);
<CheckboxItem
checked={checked}
onCheckedChange={setChecked}
/>
```
Previously that would result in a type error, because `setChecked` didn't permit indeterminate states. However, `CheckboxItem` never actually sets itself into an indeterminate state—that can only be set via props—meaning we shouldn't have to support that case if we don't want to.
I've marked this as a patch version because, despite changing a type definition, function types are contravariant in TypeScript, i.e. any function which is assignable to `(value: boolean | …
> [Menu] Only require onCheckedChange to handle boolean values

- .github/workflows/chromatic.yml
- .github/workflows/version.yml
- .yarn/versions/170035f7.yml
Chromatic and Version check actions were failing at the installation step due to a mismatch in node version when running locally vs CI.
This change pins these actions to use the version specified in `.nvmrc`, resolving the issue.
> Fix failing dependency installations in CI

- .yarn/versions/c47b2fc0.yml
- packages/react/popper/src/Popper.tsx
[Reset the middleware lifecycle](https://floating-ui.com/docs/middleware#resetting-the-lifecycle) to calculate the right position when using `--radix-popper-anchor-width` or `--radix-popper-anchor-height`.
See the behavior in some primitives although works with `Select`
https://codesandbox.io/p/sandbox/cocky-wood-wgqnuy
Fixes #1968
Fixes #2017
> Fix position when use anchor css properties

- .yarn/versions/fd8abcfb.yml
- packages/react/accordion/src/Accordion.tsx
Makes use of the existing `getState` function in AccordionItem
> [Accordion] Refactor AccordionItem data-state to use getState helper

- .yarn/versions/e5a492df.yml
- cypress/integration/Dialog.spec.ts
- packages/react/dialog/src/Dialog.stories.tsx
- packages/react/focus-scope/src/FocusScope.stories.tsx
- packages/react/focus-scope/src/FocusScope.tsx
> [FocusScope] Maintain trap when deleting focused element

- .yarn/versions/09c74da3.yml
- packages/react/popover/src/Popover.stories.tsx
- packages/react/popper/package.json
- packages/react/popper/src/Popper.tsx
- yarn.lock
This PR upgrades major version of `@floating-ui/react-dom` in `Popper` component.
Noticeble release notes from Floating UI:
- https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Fcore%401.0.0
- https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Fdom%401.2.5
- https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Freact-dom%401.1.0
- https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Freact-dom%401.0.1
- https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Freact-dom%402.0.0
The PR does the following:
- Upgrades `@floating-ui/react-dom` to `2.0.0`.
- Changes  `@floating-ui/react-dom` from fixed version to minor version. Since Floating UI uses semantic versioning, it should be safe to use …
> [Popper] Upgrade floating-ui

- .yarn/versions/03e4cd61.yml
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
These changes introduce an onClick event handler for the Select scroll buttons for better user experience on touch devices. This issue was highlighted by our QA engineer that scrolling the Select content with swipe gestures might not be obvious to some users. If they tried to click on the scroll buttons, nothing happened. After this change, clicking on the scroll buttons scrolls the viewport.
This change only enhances the touch experience. To test, 
1. Navigate to the Select Within Dialog story http://localhost:9009/?path=/story/components-select--within-dialog
2. Open browser devtools and enable mobile mode
3. Open the select and click on the scroll buttons
https://user-images.githubusercontent.com/36122/200658548-28ee7a1a-cb15-42ce-96cc-9eacdc11aaae.mov
> [Select] add scroll button onClick for better touch experience

- .yarn/versions/2590f83c.yml
- packages/react/tooltip/src/Tooltip.tsx
https://github.com/radix-ui/primitives/assets/6387301/e866a6e2-dec5-4d35-b69b-c03cdac432bb
Following up on discussion in [#2148](https://github.com/radix-ui/primitives/pull/2148) and prior work in #1960, this PR improves the grace area calculation for the Tooltip component (closing #1855). The approach here approach follows the logic outlined by @benoitgrelard in #1960: Instead of a single start point, the logic now pre-appends two start points which are determined as follows relative to the exit point:
Given a side ("top" | "bottom" | "left" | "right"):
- the two points should extend along that side in both directions
- the two points should be pushed towards the the opposite side
Closes #1855
> [Tooltip] Improve grace area calculation

- .yarn/versions/8e903555.yml
- packages/react/scroll-area/src/ScrollArea.tsx
> [ScrollArea] `scroll-behavior: smooth` compatibility

- .yarn/versions/852d0fe8.yml
- packages/react/dismissable-layer/src/DismissableLayer.tsx
The click event is not properly cleared when canceled on touch devices, causing content to close when clicked inside.
Fixes https://github.com/radix-ui/primitives/issues/2171
> Fix dispatch onPointerDownOutside on touch when click inside

- .yarn/versions/ca844fc6.yml
- packages/react/dialog/src/Dialog.tsx
- packages/react/hover-card/src/HoverCard.tsx
- packages/react/menu/src/Menu.tsx
- packages/react/popover/src/Popover.tsx
- packages/react/portal/src/Portal.tsx
- packages/react/select/src/Select.tsx
- packages/react/tooltip/src/Tooltip.tsx
Removed primitive element types from `Portal` part in all primitives and added JSDoc to the `container` prop in the `Portal` utility
Fixes #1974
> Remove primitive element types from `Portal` part

- .yarn/versions/6d1dbdd9.yml
- packages/react/popper/src/Popper.stories.tsx
- packages/react/popper/src/Popper.tsx
Allow passing [autoUpdateOptions](https://floating-ui.com/docs/autoupdate#options) to floating-ui, which allows using requestAnimationFrame to keep tooltip attached to element that is being moved programmatically.  Not sure if this is the ideal API for enabling this behavior (maybe a boolean prop like `enableRequestAnimationFrameUpdate` or something would be simpler), feel free to change.
Originally asked about this here: https://github.com/radix-ui/primitives/discussions/2006
Closes #1612
Closes #2006
> [Popper] Add option to always re-position popper (rAF-based)

- .yarn/versions/dd1eb89d.yml
- packages/react/scroll-area/src/ScrollArea.tsx
- packages/react/select/src/Select.tsx
Added `nonce` prop to be able to pass CSP nonce to components which explicitly render inline styles.
Solves https://github.com/radix-ui/primitives/issues/2057
> feat: added CSP nonce prop

- .yarn/versions/f4333956.yml
- packages/react/roving-focus/src/RovingFocusGroup.tsx
> [RovingFocusGroup] Move only with single arrow keys

- .yarn/versions/5793010b.yml
- packages/react/popper/src/Popper.tsx
When using `hideWhenDetached`, the opacity is changed to 0 instead of the visibility. This lets users click items that they cannot see. This is generally a bad user experience.
This patch updates the `Popper` to set the `visibility` to `hidden` when `hideWhenDetached` is used. This ensures the user cannot interact with the hidden element.
This aligns with what is in the `@floating-ui/react-dom` documentation.
Ref: https://floating-ui.com/docs/hide#usage
Closes: https://github.com/radix-ui/primitives/issues/2743
> fix(Popper): use `visibility` to hide instead of `opacity`

- .yarn/versions/dc4b1017.yml
- packages/react/popper/src/Popper.tsx
This patch sets `pointer-events: none` when the `<PopperContent>` is hidden so that the UI behaves as if it is not there at all. This ensures that users can interact with elements beneath the `<PopperContent>` uninterrupted.
Ref: https://github.com/radix-ui/primitives/issues/2743#issuecomment-1971843131
Fixes: e5ba0d9a0944 ("fix(Popper): use `visibility` to hide instead of `opacity` (#2744)")
> fix(Popper): disable pointer events when hidden

- .yarn/versions/ded3a040.yml
- packages/react/label/src/Label.stories.tsx
- packages/react/label/src/Label.tsx
We were a bit too eager with preventing double-click, causing issues with double-clicking on arrows in a number input for example.
Fixes  #2656
> [Label] Don't eagerly prevent double-click

- .yarn/versions/75dcd823.yml
- packages/react/use-escape-keydown/src/useEscapeKeydown.tsx
> Use capture phase in `useEscapeKeydown`

- .yarn/versions/2ab74363.yml
- packages/react/menu/src/Menu.tsx
- packages/react/roving-focus/src/RovingFocusGroup.tsx
> [DropdownMenu] Prevent scroll on initial menu focus

- .yarn/versions/c9fc51b8.yml
- packages/react/progress/src/Progress.stories.tsx
- packages/react/progress/src/Progress.tsx
I've discovered new errors in the console for undefined Progress values in the recent RC:
***
Digging in, in #2934, a [loose null comparison](https://github.com/radix-ui/primitives/pull/2934/files#diff-44b69285a9a3964d445cfdbd921ebadc4140b249f1002db2cd3eeae31b2fed59L79) for `valueProp != null` was [changed](https://github.com/radix-ui/primitives/pull/2934/files#diff-44b69285a9a3964d445cfdbd921ebadc4140b249f1002db2cd3eeae31b2fed59R46) to a strict `valueProp !== null` as that seemed to reflect the intention of the code better given the related error message that it rendered.
This restores the previous behaviour of undefined value considered valid for forward compatibility
> [Progress] Assume indeterminate value

- .yarn/versions/261663d9.yml
- packages/react/dialog/src/Dialog.test.tsx
- packages/react/dialog/src/Dialog.tsx
- Dialog primitive was supposed to throw errors when there was a missing title because that’s an A11Y violation; also it was supposed to show a console warning for missing descriptions
- However, that didn’t actually work in practice—I confirmed that in CodeSandbox for different primitive versions (tested 0.1.7, 1.0.0, and a bunch of versions leading up to 1.1.0-rc.3) and different React versions
- The above code started working after the [changes to the build process](https://github.com/radix-ui/primitives/pull/2922)
- The build changes “fixed” errors not being thrown, but that now breaks your app when upgrading if you missed the title
- For forward compatibility, I'm changing the thrown errors to `console.error` to avoid new runtime failures after upgrades
> [Dialog] Log error instead of throwing for missing titles

- .yarn/versions/54d1ffa8.yml
- packages/react/menu/src/Menu.tsx
By default, when a menu item is focused, browsers will scroll it into view. Sometimes even into the centre of the view. This is good when using a keyboard, because the focused item is automatically visible, but when it was focused in response to mouse movement, it has the effect of moving the item out from underneath the pointer.
Fixes radix-ui/primitives#1566
> [Menu] Don’t scroll menus in response to hover

- .yarn/versions/6945cc14.yml
- packages/react/tooltip/src/Tooltip.tsx
- packages/react/tooltip/src/index.ts
Exports back previously exported type. It's also used when generating [shadcn-ui/tooltip](https://ui.shadcn.com/docs/components/tooltip).
Fixes [#2978](https://github.com/radix-ui/primitives/issues/2978)
Similar to [#2968](https://github.com/radix-ui/primitives/pull/2968), but for Tooltip.
> [Tooltip] Export type tooltip provider props

- .yarn/versions/a54ad5a9.yml
- packages/react/scroll-area/src/ScrollArea.stories.tsx
- packages/react/scroll-area/src/ScrollArea.tsx
- ssr-testing/app/scroll-area/page.tsx
- Fix `asChild` prop not working as expected on the Viewport part
- Rework the inner content element styles on the Viewport part
- Replace `display: table` with flex styles on the parent that allow the viewport to fill container height (based on the [Radix Themes implementation](https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/components/scroll-area.css#L40))
- Replace most related inline styles with 0,0,0 specificity styles for easier overrides via `[data-radix-scroll-area-content]`
- Fix `text-overflow: ellipsis` not working when used with a vertical scrollbar
Closes #926 #1666
> [ScrollArea] Viewport fixes

- .github/CONTRIBUTING.md
Corrected the numbered list in the `CONTRIBUTING.md` document so that the numbers are sequential.
> Correct numbered list in CONTRIBUTING.md

- .yarn/versions/cc138cf5.yml
- packages/react/select/src/Select.stories.tsx
- packages/react/select/src/Select.tsx
- Fix an issue when clicking a Select Item would click an element behind it on Android touch devices (https://github.com/radix-ui/primitives/issues/1658)
- Reproducible in Chrome’s touch device simulator
- Fix an issue when Select Trigger would open inadvertently on touch-based scroll (https://github.com/radix-ui/primitives/issues/1912) 
- Reproducible on iOS and in Chrome’s touch device simulator
- Similarly to the above, but in an open menu, prevent touch-based scrolling over Select Items from yielding a weird half-working focus interactions, and change Select Items to active on "click" for touch devices instead
The dropdown menu and potentially a couple other primitives would need similar fixes up next (can be done separately)
Touch, before: …
> [Select] Fix touch devices bugs

- .yarn/versions/8a3bd6ee.yml
- packages/react/presence/src/Presence.stories.tsx
- packages/react/presence/src/Presence.tsx
Make sure that `onAnimationEnd` is fired for consumers, after the closing animation of a component.
Fixes: #1020
_I hit #1020 when implementing an imperative API over toasts, where I want to remove a toast from the list of open toasts after it finishes its "close" animation. I expect wanting to know when an element finishes closing to be a relatively common need._
> [Presence] Ensure `onAnimationEnd` when closing

- .yarn/versions/a0df87d9.yml
- packages/react/checkbox/src/Checkbox.test.tsx
- packages/react/checkbox/src/Checkbox.tsx
Fix #2133.
There are two modes to consider: controlled and uncontrolled.
In uncontrolled mode, the `defaultChecked` property of the input should match the `defaultChecked` prop of the Checkbox.
In controlled mode, the `defaultChecked` property of the input should be set to the initial checked state of the Checkbox.
Tests have been added.
> Fix checkbox  defaultChecked unexpected changing in form

- packages/react/navigation-menu/src/NavigationMenu.tsx
This is the same change as in #1300, but for NavigationMenu. The change allows us to pass children to  `NavigationMenu.Viewport` when using the `asChild` prop.
Referenced issue: https://github.com/radix-ui/primitives/issues/1284.
Thanks ✌️
> [NavigationMenu] Allow `children` in `Viewport` types

- packages/react/id/src/id.tsx
allows radix to use React.useId on react v18+ and custom implementation on react@17.
proposed fix for https://github.com/radix-ui/primitives/issues/2796
> Use obfusctaed reference to React.useId

- .yarn/versions/c80771b8.yml
- packages/react/context/src/createContext.tsx
* add React.FC type in Provider
* just Function has not displayName type but React.FC has displayName type
* make the format the same with CollectionProvider
> refactor(context): add React.FC type in Provider

- .yarn/versions/4c2c950e.yml
- packages/react/focus-guards/src/FocusGuards.tsx
`createFocusGuard` creates a `<span>`, then applies CSS to it using `cssText`. This violates Content-Security-Policy unless `style-src: 'unsafe-inline'` is permitted. Setting the individual properties is acceptable under a strict CSP.
> Remove use of `cssText` in react-focus-guards

- .yarn/versions/8cb19c89.yml
- packages/react/dialog/package.json
- packages/react/dismissable-layer/package.json
- packages/react/menu/package.json
- packages/react/popover/package.json
- packages/react/select/package.json
- yarn.lock
Fix #1554
**Note:** This modification also affects the `shadcn/ui` Dialog.
https://ui.shadcn.com/docs/components/dialog
> Upgrade react-remove-scroll version to 2.6.0

- packages/react/context/src/createContext.tsx
Adding an additional optional chaining operator for `scope?.[scopeName]?.[index]`. We started seeing `scope?.[scopeName]` as `undefined` after switching to [esbuild](https://github.com/radix-ui/primitives/pull/2922) under specific conditions. 
Not sure whether such situation happens because a scope is not provided or there is incorrect scope composition. Adding an extra layer of safety ensures that both `scope?.[scopeName]` and `scope?.[scopeName]?.[index]` are properly checked.
> fix: index referring to scope?.[scopeName] being undefined

- .yarn/versions/9bca397e.yml
- packages/react/slot/src/Slot.test.tsx
- packages/react/slot/src/Slot.tsx
This appears to have broken some tests. Will investigate later.
> Revert "[Slot] Deduplicate merged `className` prop (#2336)"

- .yarn/versions/2adbb5fd.yml
- packages/react/checkbox/src/Checkbox.tsx
- packages/react/radio-group/src/Radio.tsx
- packages/react/select/src/Select.tsx
- packages/react/slider/src/Slider.tsx
- packages/react/switch/src/Switch.tsx
Forwards the `form` attribute to the underlying control elements for all Radix components that render a bubble input. Closes #2530.
> Forward `form` attribute to all form control elements

- .yarn/versions/ae1744f4.yml
- packages/react/tooltip/src/Tooltip.tsx
We have a product list page with products with multiple color variants. These color variants have the Tooltip component to display the color name on hover.
We have noticed a significant amount of `clearTimeout` calls when the component with the Tooltips _unmounts_. That's interesting because it happens even when we don't trigger any of the Tooltips in the page.
After some investigation, we noticed this is caused by a `window.clearTimeout` that's happening in the component unmount.
The fix proposed is quite simple. I'm checking `openTimerRef.current` and only calling this if it's not `0`. I'm also resetting `openTimerRef.current` to `0` after each `clearTimeout()`. We have noticed a reduction in the number of `clearTimeout` calls in the unmount of this component. This means a significant …
> feat: Tooltip - Performance - avoid calling clearTimeout on unmount if timeout id is 0

- packages/react/dialog/package.json
- packages/react/dismissable-layer/package.json
- packages/react/menu/package.json
- packages/react/popover/package.json
- packages/react/select/package.json
- yarn.lock
Updated react-remove-scroll from version 2.6.0 to 2.6.1
This version resolves the peer dependency error encountered during installation when using React 19
https://github.com/theKashey/react-remove-scroll
> feat(dependencies): bump `react-remove-scroll` to v2.6.1

- .yarn/versions/63262d25.yml
- packages/react/slot/src/Slot.tsx
This PR fixes the issue with consuming any Radix UI Primitive in React 19, which will throw the following error in the console (as reported in #3224):
The error seems to arise from not checking the type of the `children` prop, which could potentially be a React Fragment that does not accept `ref` prop.
Therefore, the `ref` prop is only conditionally added to the props of the `<SlotClone>` element if `children` is not of type `React.Fragment`.
> fix: do not pass ref into SlotClone component if children is a React.Fragment

- .yarn/versions/6b740aa8.yml
- packages/react/tooltip/src/tooltip.tsx
This PR closes the tooltip automatically `onPointerDown`.
Attached are the before and after behaviours:
https://github.com/user-attachments/assets/5752322f-4afe-41c3-9d50-91d72d50b909
https://github.com/user-attachments/assets/16326be9-4a4b-4abb-b2b9-ad2dc470d6fb
> Close tooltip on pointer down

- .yarn/versions/057c467a.yml
- packages/react/alert-dialog/src/alert-dialog.tsx
- packages/react/collection/src/collection.tsx
- packages/react/dialog/src/dialog.tsx
- packages/react/menu/src/menu.tsx
- packages/react/popover/src/popover.tsx
- packages/react/primitive/src/primitive.tsx
- packages/react/select/src/select.tsx
- packages/react/slot/src/index.ts
- packages/react/slot/src/slot.tsx
- packages/react/tooltip/src/tooltip.tsx
Something that has bugged me for a while is how Radix components add a lot of noise to the component tree view in React dev tools. This largely has to do with our use of the `Slot` component, which results in a view that is hard to grok and makes it more annoying to debug with so many components just named `Slot`.
This PR introduces functions to create `Slot` and `Slottable` components with unique display names to make things a little less chaotic.
In the future I'd like to propose eliminating internal usage of `Slot` for a functional approach to actually clean up the component tree as much as possible. This is an interim solution that avoids major refactoring.
> Slottable: Improve displayName for easier debugging

- packages/react/slot/src/slot.tsx
In some cases, we can return values from the event handlers. The best use-case I have for this is the following:
```tsx
<Button
onClick={() => mutateAsync({...})}
>
```
In a case like this, we can use the fact that `mutateAsync` returns a `Promise` to automatically turn on a "loading" state on our button, and turn it off when the promise resolves/rejects.
But if `Slot` doesn't "forward" the return value of the event child handler, this use-case becomes impossible if Button is in a Slot (that also applies an onClick handler)
```tsx
<Tooltip>
<Button onClick={() => mutateAsync({...})} />
</Tooltip>
```
This PR proposes that `Slot` should return the return value of the child handler. This makes `Slot` even more "transparent" to developers using it.
---
If you like the idea of this PR, I can …
> feat(Slot): mergeProps handlers should return the value of the child handler

- .changeset/hungry-baboons-greet.md
- packages/react/checkbox/src/checkbox.tsx
- packages/react/primitive/src/primitive.tsx
- packages/react/radio-group/src/radio.tsx
- packages/react/select/src/select.tsx
- packages/react/slider/src/slider.tsx
- packages/react/switch/src/switch.tsx
- packages/react/visually-hidden/src/index.ts
- packages/react/visually-hidden/src/visually-hidden.tsx
A long-standing issue is the lack of control users have over the internal "bubble input" components we render in our form controls. Because these components are rendered as implementation details rather than exposed directly, users struggle to access or control them when they cause unexpected behaviors.
Ultimately we want users to take control of these components, and even opt-out these implementations altogether when conflicts arise. Related: https://github.com/radix-ui/primitives/issues/3365.
This PR in a small first step in that direction. Each primitive's `BubbleInput` will now use a `Primitive` node rather than the built-in JSX DOM component, and accepts forwarded refs to match the behavior of other component parts.
> Use primitives for bubble input components

- .changeset/ripe-rockets-hide.md
- packages/react/use-is-hydrated/package.json
- pnpm-lock.yaml
This PR bumps the semver range for use-sync-external-store to ensure that the installed version has an `exports` field in package.json so that it can be successfully imported
Details from the related issue #3489:
```
Error: Directory import '/home/runner/work/val.town/val.town/node_modules/use-sync-external-store/shim' is not supported resolving ES modules imported from /home/runner/work/val.town/val.town/node_modules/@radix-ui/react-use-is-hydrated/dist/index.mjs
Did you mean to import "use-sync-external-store/shim/index.js"?
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_UNSUPPORTED_DIR_IMPORT', url: 'file:///home/runner/work/val.town/val.town/node_modules/use-sync-external-store/shim' }
```
Getting the same issue trying to run tests with vitest. The line, afaict: …
> deps: Bump dependency on use-sync-external-store

- .changeset/heavy-rockets-allow.md
- apps/storybook/stories/checkbox.stories.tsx
- packages/react/checkbox/src/checkbox.test.tsx
- packages/react/checkbox/src/checkbox.tsx
- packages/react/checkbox/src/index.ts
This PR introduces new parts for the Checkbox component. This change is intended to test out a new pattern that we can replicate for other form controls.
Currently our form control components will try to detect whether or not they are associated with a form, and if so, render a hidden input so that native events bubble to the form itself. While this can make behavior feel more like native form elements, the downside is that it adds an additional element that is hard to control and not always what users expect.
The goal is the hand control back to the user. So instead of `Checkbox.Root` rendering both a provider and an input, users can opt in and render the parts that they want.
```tsx
// before
<Checkbox.Root>
<Checkbox.Indicator />
</Checkbox.Root>
// after
<Checkbox.Provider> …
```
> checkbox: Add unstable `Provider`, `Trigger` and `BubbleInput`

- .changeset/fluffy-days-kneel.md
- packages/react/one-time-password-field/src/one-time-password-field.test.tsx
- packages/react/one-time-password-field/src/one-time-password-field.tsx
close #3493 
- As stated in the [documentation](https://www.radix-ui.com/primitives/docs/components/one-time-password-field#root), change default `type` to text.
- Connect a type to input to display the input value in a different way when the type changes.
- Add test for this feature
> fix: when specifying the type of One-Time Password Field, the input is displayed as pw.

- .changeset/kind-icons-tan.md
- packages/react/one-time-password-field/src/one-time-password-field.test.tsx
- packages/react/one-time-password-field/src/one-time-password-field.tsx
close #3545 
- Add test for `disable`
- disable all inputs when `disable` is true.
> fix: [One-Time Password Field] disable all inputs when disable is true

- .changeset/nasty-pandas-float.md
- packages/react/presence/src/presence.tsx
Fixes #2763.
Using [CSS.escape](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape_static).
As I checked, this API is supported in all browsers even in the [2022 browserslist targets](https://github.com/radix-ui/primitives/discussions/1019#discussioncomment-3359338) of this project.
Further explanation of the bug:
`getComputedStyle()` returns a `CSSStyleDeclaration`, which is serialized according to the spec.
Meanwhile, the values from `AnimationEvent` are not required to be serialized (which makes sense, as it's intended for JavaScript usage, where escaping for CSS syntax is unnecessary). Therefore the `animationName` is returned as-is in the event handler, causing the mismatch.
---
Preview of the bug fix based on the original reproduction: …
> fix(Presence): handle escape characters in animation names correctly
